# Generated by Django 2.1.7 on 2021-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='DeviceLNV/ApplicationNofile/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationNofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='DeviceLNV/DeclarationNo/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=24, verbose_name='客戶別')),
                ('Plant', models.CharField(max_length=108, verbose_name='廠區')),
                ('NID', models.CharField(max_length=16, unique=True, verbose_name='設備序號')),
                ('DevID', models.CharField(max_length=128, verbose_name='設備編號')),
                ('IntfCtgry', models.CharField(max_length=64, verbose_name='介面種類')),
                ('DevCtgry', models.CharField(max_length=512, verbose_name='設備種類')),
                ('Devproperties', models.CharField(max_length=256, verbose_name='設備屬性')),
                ('DevVendor', models.CharField(max_length=128, verbose_name='設備廠家')),
                ('Devsize', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備容量')),
                ('DevModel', models.CharField(max_length=128, verbose_name='設備型號')),
                ('DevName', models.CharField(max_length=1024, verbose_name='設備名稱')),
                ('HWVer', models.CharField(blank=True, max_length=64, null=True, verbose_name='HW Ver.')),
                ('FWVer', models.CharField(blank=True, max_length=64, null=True, verbose_name='FW Ver.')),
                ('DevDescription', models.CharField(blank=True, max_length=1024, null=True, verbose_name='設備描述')),
                ('PckgIncludes', models.CharField(blank=True, max_length=512, null=True, verbose_name='附帶品')),
                ('expirdate', models.CharField(blank=True, choices=[('一年', '一年'), ('二年', '二年'), ('三年', '三年'), ('四年', '四年'), ('五年', '五年')], max_length=108, null=True, verbose_name='保固期')),
                ('DevPrice', models.CharField(blank=True, max_length=16, null=True, verbose_name='價值 RMB(單價)')),
                ('Source', models.CharField(blank=True, max_length=16, null=True, verbose_name='設備來源')),
                ('Pchsdate', models.DateField(blank=True, max_length=64, null=True, verbose_name='購買時間')),
                ('PN', models.CharField(max_length=64, verbose_name='P/N')),
                ('LSTA', models.CharField(max_length=256, verbose_name='LNV SW Test lab device Audit list: Require state(Must, Optional)')),
                ('ApplicationNo', models.CharField(max_length=64, verbose_name='申購單號')),
                ('DeclarationNo', models.CharField(max_length=64, verbose_name='報關單號')),
                ('AssetNum', models.CharField(max_length=64, verbose_name='資產編號')),
                ('addnewname', models.CharField(max_length=64, verbose_name='設備添加人員')),
                ('addnewdate', models.DateField(blank=True, max_length=64, null=True, verbose_name='addnewdate')),
                ('Comment', models.CharField(blank=True, max_length=64, null=True, verbose_name='備註')),
                ('uscyc', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用次數')),
                ('UsrTimes', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還次數')),
                ('DevStatus', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fixed', 'Fixed'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=64, null=True, verbose_name='設備狀態')),
                ('BrwStatus', models.CharField(blank=True, choices=[('已借出', '已借出'), ('可借用', '可借用'), ('預定確認', '預定確認'), ('歸還確認', '歸還確認'), ('續借確認', '續借確認')], max_length=64, null=True, verbose_name='借還狀態')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='用戶名稱')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員工號')),
                ('ProjectCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='機種')),
                ('Phase', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phase')),
                ('useday', models.CharField(blank=True, max_length=16, null=True, verbose_name='使用天數')),
                ('Plandate', models.DateField(blank=True, max_length=64, null=True, verbose_name='預計歸還日期')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='借用時間')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Last_BR_per', models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員')),
                ('Last_BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員工號')),
                ('Last_Predict_return', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次預計歸還日期')),
                ('Last_Borrow_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次借用日期')),
                ('Last_Return_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次歸還日期')),
                ('Application', models.ManyToManyField(blank=True, related_name='filesAp', to='DeviceLNV.ApplicationNofile', verbose_name='申購單')),
                ('Declaration', models.ManyToManyField(blank=True, related_name='filesDe', to='DeviceLNV.DeclarationNofile', verbose_name='報關單')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceLNVCategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntfCtgry', models.CharField(max_length=64, verbose_name='介面種類')),
                ('DevCtgry', models.CharField(max_length=512, verbose_name='設備種類')),
                ('Devproperties', models.CharField(max_length=256, verbose_name='設備屬性')),
                ('DevVendor', models.CharField(max_length=128, verbose_name='設備廠家')),
                ('Devsize', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備容量')),
            ],
        ),
    ]
