# Generated by Django 2.1.7 on 2023-02-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationNofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(upload_to='DeviceLNV/DeclarationNo/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevCtgryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevCtgry', models.CharField(max_length=512, verbose_name='設備種類')),
            ],
            options={
                'verbose_name': '設備種類',
                'verbose_name_plural': '設備種類',
            },
        ),
        migrations.CreateModel(
            name='DeviceDevpropertiesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devproperties', models.CharField(max_length=256, verbose_name='設備屬性')),
                ('DevCtgry_P', models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceDevCtgryList')),
            ],
            options={
                'verbose_name': '設備屬性',
                'verbose_name_plural': '設備屬性',
            },
        ),
        migrations.CreateModel(
            name='DeviceDevsizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devsize', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備容量')),
            ],
            options={
                'verbose_name': '設備容量',
                'verbose_name_plural': '設備容量',
            },
        ),
        migrations.CreateModel(
            name='DeviceDevVendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevVendor', models.CharField(max_length=128, verbose_name='設備廠家')),
                ('Devproperties_P', models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceDevpropertiesList')),
            ],
            options={
                'verbose_name': '設備廠家',
                'verbose_name_plural': '設備廠家',
            },
        ),
        migrations.CreateModel(
            name='DeviceIntfCtgryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntfCtgry', models.CharField(max_length=64, verbose_name='介面種類')),
            ],
            options={
                'verbose_name': '介面種類',
                'verbose_name_plural': '介面種類',
            },
        ),
        migrations.CreateModel(
            name='DeviceLNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39')], max_length=24, verbose_name='客戶別')),
                ('Plant', models.CharField(choices=[('', ''), ('KS', 'KS'), ('CQ', 'CQ')], max_length=108, verbose_name='廠區')),
                ('NID', models.CharField(max_length=16, unique=True, verbose_name='設備序號')),
                ('DevID', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備用途')),
                ('IntfCtgry', models.CharField(max_length=64, verbose_name='介面種類')),
                ('DevCtgry', models.CharField(max_length=512, verbose_name='設備種類')),
                ('Devproperties', models.CharField(max_length=256, verbose_name='設備屬性')),
                ('DevVendor', models.CharField(max_length=128, verbose_name='設備廠家')),
                ('Devsize', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備容量')),
                ('DevModel', models.CharField(max_length=128, verbose_name='設備型號')),
                ('DevName', models.CharField(max_length=1024, verbose_name='設備名稱')),
                ('HWVer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='HW Ver.')),
                ('FWVer', models.CharField(blank=True, max_length=1000, null=True, verbose_name='FW Ver.')),
                ('DevDescription', models.CharField(blank=True, max_length=1024, null=True, verbose_name='設備描述')),
                ('PckgIncludes', models.CharField(blank=True, max_length=512, null=True, verbose_name='附帶品')),
                ('expirdate', models.CharField(blank=True, choices=[('一年', '一年'), ('二年', '二年'), ('三年', '三年'), ('四年', '四年'), ('五年', '五年')], max_length=108, null=True, verbose_name='保固期')),
                ('DevPrice', models.CharField(blank=True, max_length=16, null=True, verbose_name='價值 RMB(單價)')),
                ('Source', models.CharField(blank=True, max_length=64, null=True, verbose_name='設備來源')),
                ('Pchsdate', models.DateField(blank=True, max_length=64, null=True, verbose_name='購買時間')),
                ('PN', models.CharField(blank=True, max_length=64, null=True, verbose_name='料號')),
                ('LSTA', models.CharField(blank=True, choices=[('Must', 'Must'), ('Optional', 'Optional'), ('Similar', 'Similar')], max_length=256, null=True, verbose_name='LNV SW Test lab device Audit list: Require state(Must, Optional)')),
                ('ApplicationNo', models.CharField(blank=True, max_length=64, null=True, verbose_name='申購單號')),
                ('DeclarationNo', models.CharField(blank=True, max_length=64, null=True, verbose_name='報關單號')),
                ('AssetNum', models.CharField(blank=True, max_length=64, null=True, verbose_name='資產編號')),
                ('addnewname', models.CharField(blank=True, max_length=64, null=True, verbose_name='設備添加人員')),
                ('addnewdate', models.DateField(blank=True, max_length=64, null=True, verbose_name='設備添加日期')),
                ('Comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='備註')),
                ('uscyc', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用次數')),
                ('UsrTimes', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還次數')),
                ('DevStatus', models.CharField(blank=True, choices=[('Good', 'Good'), ('Fixed', 'Fixed'), ('Long', 'Long'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=64, null=True, verbose_name='設備狀態')),
                ('BrwStatus', models.CharField(blank=True, choices=[('驗收中', '驗收中'), ('已借出', '已借出'), ('可借用', '可借用'), ('固定設備', '固定設備'), ('預定確認中', '預定確認中'), ('歸還確認中', '歸還確認中'), ('續借確認中', '續借確認中')], max_length=64, null=True, verbose_name='借還狀態')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='用戶名稱')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員工號')),
                ('ProjectCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='機種')),
                ('Phase', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phase')),
                ('useday', models.CharField(blank=True, max_length=16, null=True, verbose_name='使用天數')),
                ('Plandate', models.DateField(blank=True, max_length=64, null=True, verbose_name='預計歸還日期')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='借用時間')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('EOL', models.DateField(blank=True, max_length=64, null=True, verbose_name='EOL日期')),
                ('Last_BR_per', models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員')),
                ('Last_BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員工號')),
                ('Last_ProjectCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='最近一次借機種')),
                ('Last_Phase', models.CharField(blank=True, max_length=16, null=True, verbose_name='最近一次借Phase')),
                ('Last_Predict_return', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次預計歸還日期')),
                ('Last_Borrow_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次借用日期')),
                ('Last_Return_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次歸還日期')),
                ('Last_uscyc', models.CharField(blank=True, max_length=64, null=True, verbose_name='上次借用期間使用次數')),
                ('Declaration', models.ManyToManyField(blank=True, related_name='filesDe', to='DeviceLNV.DeclarationNofile', verbose_name='報關單')),
            ],
            options={
                'verbose_name': 'Device_LNV',
                'verbose_name_plural': 'Device_LNV',
            },
        ),
        migrations.CreateModel(
            name='DeviceLNVHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=16, verbose_name='設備序號')),
                ('DevID', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備編號')),
                ('DevModel', models.CharField(max_length=128, verbose_name='設備型號')),
                ('DevName', models.CharField(max_length=1024, verbose_name='設備名稱')),
                ('uscyc', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用次數')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='借用時間')),
                ('Plandate', models.DateField(blank=True, max_length=64, null=True, verbose_name='預計歸還日期')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='用戶名稱')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員工號')),
                ('ProjectCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='機種')),
                ('Phase', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phase')),
                ('Result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=16, null=True, verbose_name='Result')),
                ('Devstatus', models.CharField(blank=True, max_length=16, null=True, verbose_name='Devstatus')),
                ('Comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': '设备借还记录',
                'verbose_name_plural': '设备借还记录',
            },
        ),
        migrations.CreateModel(
            name='PICS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='DeviceLNV/PIC/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.AddField(
            model_name='devicelnv',
            name='Photo',
            field=models.ManyToManyField(blank=True, related_name='pics', to='DeviceLNV.PICS', verbose_name='图片表'),
        ),
        migrations.AddField(
            model_name='devicedevsizelist',
            name='DevVendor_P',
            field=models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceDevVendorList'),
        ),
        migrations.AddField(
            model_name='devicedevctgrylist',
            name='IntfCtgry_P',
            field=models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceIntfCtgryList'),
        ),
    ]
