# Generated by Django 2.1.7 on 2021-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0002_auto_20210412_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDevCtgryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevCtgry', models.CharField(max_length=512, verbose_name='設備種類')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevpropertiesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devproperties', models.CharField(max_length=256, verbose_name='設備屬性')),
                ('DevCtgry_P', models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceDevCtgryList')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevsizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devsize', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備容量')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevVendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevVendor', models.CharField(max_length=128, verbose_name='設備廠家')),
                ('Devproperties_P', models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceDevpropertiesList')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceIntfCtgryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntfCtgry', models.CharField(max_length=64, verbose_name='介面種類')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceLNVCategoryList',
        ),
        migrations.AddField(
            model_name='devicedevsizelist',
            name='DevVendor_P',
            field=models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceDevVendorList'),
        ),
        migrations.AddField(
            model_name='devicedevctgrylist',
            name='IntfCtgry_P',
            field=models.ForeignKey(on_delete=True, to='DeviceLNV.DeviceIntfCtgryList'),
        ),
    ]
