# Generated by Django 2.1.7 on 2021-04-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0003_auto_20210414_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnv',
            name='AssetNum',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='資產編號'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39')], max_length=24, verbose_name='客戶別'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='DeclarationNo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='報關單號'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='LSTA',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='LNV SW Test lab device Audit list: Require state(Must, Optional)'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='PN',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='P/N'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='Plant',
            field=models.CharField(choices=[('', ''), ('KS', 'KS'), ('CQ', 'CQ')], max_length=108, verbose_name='廠區'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='addnewname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='設備添加人員'),
        ),
    ]
