# Generated by Django 2.1.7 on 2021-04-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0004_auto_20210414_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicedevctgrylist',
            options={'verbose_name': '設備種類', 'verbose_name_plural': '設備種類'},
        ),
        migrations.AlterModelOptions(
            name='devicedevpropertieslist',
            options={'verbose_name': '設備屬性', 'verbose_name_plural': '設備屬性'},
        ),
        migrations.AlterModelOptions(
            name='devicedevsizelist',
            options={'verbose_name': '設備容量', 'verbose_name_plural': '設備容量'},
        ),
        migrations.AlterModelOptions(
            name='devicedevvendorlist',
            options={'verbose_name': '設備廠家', 'verbose_name_plural': '設備廠家'},
        ),
        migrations.AlterModelOptions(
            name='deviceintfctgrylist',
            options={'verbose_name': '介面種類', 'verbose_name_plural': '介面種類'},
        ),
    ]
