# Generated by Django 2.1.7 on 2021-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0007_auto_20210621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnv',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('已借出', '已借出'), ('可借用', '可借用'), ('固定設備', '固定設備'), ('預定確認中', '預定確認中'), ('歸還確認中', '歸還確認中'), ('續借確認中', '續借確認中')], max_length=64, null=True, verbose_name='借還狀態'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='LSTA',
            field=models.CharField(blank=True, choices=[('Must', 'Must'), ('Optional', 'Optional'), ('Similar', 'Similar')], max_length=256, null=True, verbose_name='LNV SW Test lab device Audit list: Require state(Must, Optional)'),
        ),
    ]
