# Generated by Django 2.1.7 on 2021-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0008_auto_20210629_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnv',
            name='Source',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='設備來源'),
        ),
    ]
