# Generated by Django 2.1.7 on 2021-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0012_devicelnvhis_plandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelnvhis',
            name='Phase',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='devicelnvhis',
            name='ProjectCode',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='機種'),
        ),
    ]
