# Generated by Django 2.1.7 on 2021-08-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0014_auto_20210818_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnvhis',
            name='NID',
            field=models.CharField(max_length=16, verbose_name='設備序號'),
        ),
    ]
