# Generated by Django 2.1.7 on 2021-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0015_auto_20210819_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelnv',
            name='Last_uscyc',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上次借用期間使用次數'),
        ),
    ]
