# Generated by Django 2.1.7 on 2021-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0018_auto_20210901_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnv',
            name='HWVer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='HW Ver.'),
        ),
    ]
