# Generated by Django 2.1.7 on 2021-09-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0019_auto_20210901_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelnvhis',
            name='Devstatus',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Devstatus'),
        ),
        migrations.AddField(
            model_name='devicelnvhis',
            name='Result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=16, null=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('已借出', '已借出'), ('可借用', '可借用'), ('固定設備', '固定設備'), ('長期借用', '長期借用'), ('預定確認中', '預定確認中'), ('歸還確認中', '歸還確認中'), ('續借確認中', '續借確認中')], max_length=64, null=True, verbose_name='借還狀態'),
        ),
    ]
