# Generated by Django 2.1.7 on 2021-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceLNV', '0020_auto_20210909_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelnv',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('驗收中', '驗收中'), ('已借出', '已借出'), ('可借用', '可借用'), ('固定設備', '固定設備'), ('預定確認中', '預定確認中'), ('歸還確認中', '歸還確認中'), ('續借確認中', '續借確認中')], max_length=64, null=True, verbose_name='借還狀態'),
        ),
        migrations.AlterField(
            model_name='devicelnv',
            name='DevStatus',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fixed', 'Fixed'), ('Long', 'Long'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=64, null=True, verbose_name='設備狀態'),
        ),
    ]
