# Generated by Django 2.1.7 on 2020-07-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LessonProjectME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QIL_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100, verbose_name='Product')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('T88(AIO)', 'T88(AIO)'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('QIL_No', models.CharField(max_length=100, unique=True, verbose_name='QIL_No')),
                ('Issue_Description', models.CharField(max_length=3000, verbose_name='Issue_Description')),
                ('Root_Cause', models.CharField(max_length=3000, verbose_name='Root_Cause')),
                ('Status', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('T88(AIO)', 'T88(AIO)'), ('Others', 'Others')], max_length=100, verbose_name='Status')),
                ('Creator', models.CharField(default='', max_length=100)),
                ('Created_On', models.CharField(default='', max_length=26, verbose_name='Created_On')),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(blank=True, max_length=26, verbose_name='edit_time')),
            ],
            options={
                'verbose_name': 'QIL_M',
                'verbose_name_plural': 'QIL_M',
            },
        ),
        migrations.CreateModel(
            name='QIL_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('', ''), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/S', 'N/S'), ('N/A', 'N/A')], max_length=20)),
                ('Comment', models.CharField(max_length=1000)),
                ('editor', models.CharField(default='', max_length=100)),
                ('edit_time', models.CharField(blank=True, default='', max_length=26, verbose_name='edit_time')),
                ('Projectinfo', models.ForeignKey(on_delete=True, to='LessonProjectME.TestProjectLL')),
                ('QIL', models.ForeignKey(on_delete=True, to='QIL.QIL_M')),
            ],
        ),
    ]
