# Generated by Django 2.1.7 on 2020-07-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QIL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_QIL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_qil/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.AddField(
            model_name='qil_m',
            name='files_QIL',
            field=models.ManyToManyField(blank=True, related_name='files_QIL', to='QIL.files_QIL', verbose_name='图文件表'),
        ),
    ]
