# Generated by Django 2.1.7 on 2020-12-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QIL', '0002_auto_20201223_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qil_m',
            name='Status',
            field=models.CharField(choices=[('', ''), ('Closed', 'Closed'), ('Deleted', 'Deleted'), ('In Process', 'In Process'), ('Lesson Learn', 'Lesson Learn'), ('Open', 'Open')], max_length=100, verbose_name='Status'),
        ),
    ]
