# Generated by Django 2.1.7 on 2024-01-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LowLightList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('T88(NB)', 'T88(NB)'), ('ABO', 'ABO'), ('Others', 'Others')], max_length=100, verbose_name='Customer')),
                ('ProjectCompal', models.CharField(max_length=100, verbose_name='ProjectCompal')),
                ('Lowlight_item', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lowlight_item')),
                ('Root_Cause', models.CharField(max_length=5000, verbose_name='Root_Cause')),
                ('LD', models.CharField(max_length=100, verbose_name='LD')),
                ('Owner', models.CharField(blank=True, max_length=200, null=True, verbose_name='Owner')),
                ('Mitigation_plan', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Mitigation_plan')),
                ('editor', models.CharField(max_length=100, verbose_name='editor')),
                ('edit_time', models.DateTimeField(verbose_name='edit_time')),
            ],
            options={
                'verbose_name': 'LowLightList',
                'verbose_name_plural': 'LowLightList',
            },
        ),
    ]
