# Generated by Django 2.1.7 on 2024-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('T88(NB)', 'T88(NB)'), ('ABO', 'ABO'), ('Others', 'Others')], max_length=100, verbose_name='Customer')),
                ('Project', models.CharField(max_length=100, verbose_name='Project')),
                ('FFRT_Entry_unclose_issue', models.CharField(blank=True, max_length=10, null=True, verbose_name='FFRT_Entry_unclose_issue')),
                ('SIT_Exit_unclose_issue', models.CharField(blank=True, max_length=10, null=True, verbose_name='SIT_Exit_unclose_issue')),
                ('first_FFRT', models.CharField(blank=True, max_length=21, null=True, verbose_name='first_FFRT')),
                ('second_FFRT', models.CharField(blank=True, max_length=21, null=True, verbose_name='second_FFRT')),
                ('third_FFRT', models.CharField(blank=True, max_length=21, null=True, verbose_name='third_FFRT')),
                ('fourth_FFRT', models.CharField(blank=True, max_length=21, null=True, verbose_name='fourth_FFRT')),
                ('fifth_FFRT', models.CharField(blank=True, max_length=21, null=True, verbose_name='fifth_FFRT')),
                ('sixth_FFRT', models.CharField(blank=True, max_length=21, null=True, verbose_name='sixth_FFRT')),
                ('issue_def', models.CharField(blank=True, max_length=50, null=True, verbose_name='issue_def')),
                ('Remark', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Remark')),
                ('FFRT', models.CharField(blank=True, max_length=20, null=True, verbose_name='FFRT')),
                ('Defect_ID', models.CharField(blank=True, max_length=20, null=True, verbose_name='Defect_ID')),
                ('Title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Title')),
                ('Create_date', models.DateTimeField(verbose_name='Create_date')),
                ('Update_date', models.DateTimeField(verbose_name='Update_date')),
                ('Status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('Severity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Severity')),
                ('Category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('Component', models.CharField(blank=True, max_length=200, null=True, verbose_name='Component')),
                ('BIOS_KBC', models.CharField(blank=True, max_length=100, null=True, verbose_name='BIOS_KBC')),
                ('Comments', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Comments')),
                ('Author', models.CharField(blank=True, max_length=200, null=True, verbose_name='Author')),
                ('Assign_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assign_to')),
                ('Description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('Reproduce_steps', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Reproduce_steps')),
                ('Age', models.CharField(blank=True, max_length=10, null=True, verbose_name='Age')),
            ],
            options={
                'verbose_name': 'LowLightList',
                'verbose_name_plural': 'LowLightList',
            },
        ),
    ]
