# Generated by Django 2.1.7 on 2024-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssuesBreakdown', '0002_auto_20240123_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuesbreakdown',
            options={'verbose_name': 'IssuesBreakdown', 'verbose_name_plural': 'IssuesBreakdown'},
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='Assign_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Assign to'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='BIOS_KBC',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BIOS/KBC'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='Create_date',
            field=models.DateTimeField(verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='Defect_ID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Defect ID'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='FFRT_Entry_unclose_issue',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='FFRT Entry unclose issue'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='Reproduce_steps',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Reproduce steps'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='SIT_Exit_unclose_issue',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SIT Exit unclose issue'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='Update_date',
            field=models.DateTimeField(verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='fifth_FFRT',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='5th FFRT'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='first_FFRT',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='1st FFRT'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='fourth_FFRT',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='4th FFRT'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='issue_def',
            field=models.CharField(blank=True, choices=[('', ''), ('New found_Unidentified', 'New found_Unidentified'), ('New found_MWD', 'New found_MWD'), ('New found_New Implement', 'New found_New Implement'), ('New found_Stress', 'New found_Stress'), ('Regression Fail', 'Regression Fail'), ('UE', 'UE'), ('Adhoc', 'Adhoc'), ('Late found', 'Late found')], max_length=50, null=True, verbose_name='分類'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='second_FFRT',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='2nd FFRT'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='sixth_FFRT',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='6th FFRT'),
        ),
        migrations.AlterField(
            model_name='issuesbreakdown',
            name='third_FFRT',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='3rd FFRT'),
        ),
    ]
