# Generated by Django 2.1.7 on 2020-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files_SpecD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_SpecD/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='SpecDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=20, verbose_name='Customer')),
                ('Category', models.CharField(max_length=20, verbose_name='Category')),
                ('Functionn', models.CharField(max_length=50, verbose_name='Functionn')),
                ('Case_name', models.CharField(max_length=1000, verbose_name='Case_name')),
                ('Version', models.CharField(max_length=20, verbose_name='Version')),
                ('editor', models.CharField(max_length=100, verbose_name='editor')),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
                ('files_Spec', models.ManyToManyField(blank=True, related_name='files_SpecD', to='SpecDownload.files_SpecD', verbose_name='图文件表')),
            ],
        ),
    ]
