# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'title.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tile(object):
    def setupUi(self, tile):
        tile.setObjectName("tile")
        tile.resize(472, 279)
        self.centralwidget = QtWidgets.QWidget(tile)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 311, 211))
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 130, 54, 20))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 210, 71, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 130, 71, 20))
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 160, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 54, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 180, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        tile.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(tile)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        tile.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(tile)
        self.statusbar.setObjectName("statusbar")
        tile.setStatusBar(self.statusbar)
        self.actionda = QtWidgets.QAction(tile)
        self.actionda.setObjectName("actionda")
        self.actiondakai = QtWidgets.QAction(tile)
        self.actiondakai.setCheckable(False)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        self.actiondakai.setFont(font)
        self.actiondakai.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actiondakai.setPriority(QtWidgets.QAction.NormalPriority)
        self.actiondakai.setObjectName("actiondakai")
        self.menu.addAction(self.actiondakai)
        self.menu.addAction(self.actionda)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(tile)
        QtCore.QMetaObject.connectSlotsByName(tile)

    def retranslateUi(self, tile):
        _translate = QtCore.QCoreApplication.translate
        tile.setWindowTitle(_translate("tile", "分块"))
        self.label.setText(_translate("tile", "分块大小："))
        self.pushButton.setText(_translate("tile", "分块"))
        self.lineEdit.setText(_translate("tile", "256"))
        self.lineEdit.setPlaceholderText(_translate("tile", "256"))
        self.label_2.setText(_translate("tile", "输出路径："))
        self.label_3.setText(_translate("tile", "影像列表："))
        self.menu.setTitle(_translate("tile", "文件"))
        self.actionda.setText(_translate("tile", "打开文件夹"))
        self.actiondakai.setText(_translate("tile", "打开文件"))

