# Generated by Django 2.1.7 on 2020-12-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='local_identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincecode', models.CharField(max_length=6, verbose_name='provincecode')),
                ('provincevalue', models.CharField(max_length=50, verbose_name='provincevalue')),
                ('citycode', models.CharField(max_length=6, verbose_name='citycode')),
                ('cityvalue', models.CharField(max_length=50, verbose_name='cityvalue')),
                ('countycode', models.CharField(max_length=6, verbose_name='countycode')),
                ('countyvalue', models.CharField(max_length=50, verbose_name='countyvalue')),
                ('longitude', models.CharField(max_length=6, verbose_name='longitude')),
                ('latitude', models.CharField(max_length=100, verbose_name='latitude')),
            ],
        ),
    ]
