# Generated by Django 2.1.7 on 2023-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0002_publicaream'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='transferDate',
            field=models.DateField(blank=True, null=True, verbose_name='轉職日期'),
        ),
        migrations.AddField(
            model_name='personalinfohisbyyear',
            name='transferDate',
            field=models.DateField(blank=True, null=True, verbose_name='轉職日期'),
        ),
    ]
