# Generated by Django 2.1.7 on 2020-12-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0002_auto_20201221_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': '部门信息', 'verbose_name_plural': '部门信息'},
        ),
        migrations.AlterModelOptions(
            name='leaveinfo',
            options={'verbose_name': '请假信息', 'verbose_name_plural': '请假信息'},
        ),
        migrations.AlterModelOptions(
            name='local_identity',
            options={'verbose_name': '地区代码', 'verbose_name_plural': '地区代码'},
        ),
        migrations.AlterModelOptions(
            name='mainpower',
            options={'verbose_name': '人力信息', 'verbose_name_plural': '人力信息'},
        ),
        migrations.AlterModelOptions(
            name='majorifo',
            options={'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': '人员信息', 'verbose_name_plural': '人员信息'},
        ),
        migrations.AlterModelOptions(
            name='personalinfohisbyper',
            options={'verbose_name': '人员晋升历史', 'verbose_name_plural': '人员晋升历史'},
        ),
        migrations.AlterModelOptions(
            name='personalinfohisbyyear',
            options={'verbose_name': '往年人员信息', 'verbose_name_plural': '往年人员信息'},
        ),
        migrations.AlterModelOptions(
            name='portraits',
            options={'verbose_name': '头像', 'verbose_name_plural': '头像'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': '职位信息', 'verbose_name_plural': '职位信息'},
        ),
        migrations.AlterModelOptions(
            name='workovertime',
            options={'verbose_name': '加班信息', 'verbose_name_plural': '加班信息'},
        ),
        migrations.RemoveField(
            model_name='positions',
            name='Year',
        ),
        migrations.AlterField(
            model_name='departments',
            name='BU',
            field=models.CharField(max_length=50, verbose_name='部'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='CHU',
            field=models.CharField(max_length=50, verbose_name='处'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Companys',
            field=models.CharField(max_length=100, verbose_name='公司別'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Customer',
            field=models.CharField(max_length=50, verbose_name='客户别'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Department_Code',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='KE',
            field=models.CharField(max_length=50, verbose_name='课'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Manager',
            field=models.CharField(max_length=50, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Plants',
            field=models.CharField(max_length=100, verbose_name='厂区'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Year',
            field=models.CharField(max_length=100, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='PersonalInfo.Departments', verbose_name='上级部门'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Absenteeism',
            field=models.CharField(max_length=10, verbose_name='矿工'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Bereavement',
            field=models.CharField(max_length=10, verbose_name='丧假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='CNName',
            field=models.CharField(max_length=50, verbose_name='请假人姓名'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Compensatory',
            field=models.CharField(max_length=10, verbose_name='补休'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Department_Code',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='EpidemicPrevention',
            field=models.CharField(max_length=10, verbose_name='防疫假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='GroupNum',
            field=models.CharField(max_length=50, verbose_name='请假人工号'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Lactation',
            field=models.CharField(max_length=10, verbose_name='哺乳假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Marriage',
            field=models.CharField(max_length=10, verbose_name='婚假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Maternity',
            field=models.CharField(max_length=10, verbose_name='产假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Matters',
            field=models.CharField(max_length=10, verbose_name='事假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='MattersContinuation',
            field=models.CharField(max_length=10, verbose_name='续事假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Mounth',
            field=models.CharField(max_length=10, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='NoScheduling',
            field=models.CharField(max_length=10, verbose_name='无排程假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='OffDuty',
            field=models.CharField(max_length=10, verbose_name='不上班假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Others',
            field=models.CharField(max_length=10, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='PaternityLeave',
            field=models.CharField(max_length=10, verbose_name='陪产假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='PregnancyExamination',
            field=models.CharField(max_length=10, verbose_name='产检假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='PublicHoliday',
            field=models.CharField(max_length=10, verbose_name='公假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Sick',
            field=models.CharField(max_length=10, verbose_name='病假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='SickContinuation',
            field=models.CharField(max_length=10, verbose_name='续病假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Special',
            field=models.CharField(max_length=10, verbose_name='特休假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Total',
            field=models.CharField(max_length=10, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='WorkInjury',
            field=models.CharField(max_length=10, verbose_name='工伤假'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='Year',
            field=models.CharField(max_length=10, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='BU',
            field=models.CharField(max_length=50, verbose_name='部'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='CHU',
            field=models.CharField(max_length=50, verbose_name='处'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Companys',
            field=models.CharField(max_length=100, verbose_name='公司别'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Customer',
            field=models.CharField(max_length=50, verbose_name='客户别'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='DepartmentCode',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Item',
            field=models.CharField(max_length=100, verbose_name='项次'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='KE',
            field=models.CharField(max_length=50, verbose_name='课'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Plants',
            field=models.CharField(max_length=100, verbose_name='厂区'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Positions_Name',
            field=models.CharField(max_length=50, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Year',
            field=models.CharField(max_length=100, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='majorifo',
            name='Categories',
            field=models.CharField(max_length=20, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='majorifo',
            name='Education',
            field=models.CharField(max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='majorifo',
            name='Major',
            field=models.CharField(max_length=100, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='majorifo',
            name='MajorForExcel',
            field=models.CharField(max_length=100, verbose_name='专业公式查找'),
        ),
        migrations.AlterField(
            model_name='majorifo',
            name='Subject',
            field=models.CharField(max_length=100, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='majorifo',
            name='category',
            field=models.CharField(max_length=100, verbose_name='门类'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Aalary',
            field=models.CharField(max_length=50, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='CNName',
            field=models.CharField(max_length=50, verbose_name='中文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Customer',
            field=models.CharField(max_length=20, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Department',
            field=models.CharField(max_length=50, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='DepartmentCode',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='ENLevel',
            field=models.CharField(max_length=500, verbose_name='英语'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Education',
            field=models.CharField(max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='EngName',
            field=models.CharField(max_length=50, verbose_name='英文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Experience',
            field=models.CharField(max_length=20, verbose_name='是否承认工作经验'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='GraduationYear',
            field=models.CharField(max_length=20, verbose_name='毕业年度'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='GroupNum',
            field=models.CharField(max_length=50, verbose_name='集团员工'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='IdCard',
            field=models.CharField(max_length=500, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='LastAchievements',
            field=models.CharField(max_length=10, verbose_name='最后一次绩效'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='LastPromotionData',
            field=models.DateField(null=True, verbose_name='最后一次晋升日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Major',
            field=models.CharField(max_length=500, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='MajorAscription',
            field=models.CharField(max_length=500, verbose_name='专业归属'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='MobileNum',
            field=models.CharField(max_length=20, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='NativeCity',
            field=models.CharField(max_length=100, verbose_name='籍贯地市'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='NativeCounty',
            field=models.CharField(max_length=100, verbose_name='籍贯县市'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='NativeProvince',
            field=models.CharField(max_length=100, verbose_name='籍贯省份'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='NewCompany',
            field=models.CharField(max_length=100, verbose_name='新公司名称'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PlanQuitDate',
            field=models.DateField(null=True, verbose_name='预计离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Portrait',
            field=models.ForeignKey(blank=True, on_delete=True, related_name='Portrait', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PositionNow',
            field=models.CharField(max_length=20, verbose_name='现职称'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PositionTimes',
            field=models.CharField(max_length=20, verbose_name='晋升次数'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='QuitDate',
            field=models.DateField(null=True, verbose_name='离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='QuitDetail',
            field=models.CharField(max_length=1000, verbose_name='离职详情'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='QuitReason',
            field=models.CharField(max_length=100, verbose_name='离职原因'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='RegistPosition',
            field=models.CharField(max_length=20, verbose_name='入职职称'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='RegistrationDate',
            field=models.DateField(null=True, verbose_name='报道日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='ResidenceCity',
            field=models.CharField(max_length=100, verbose_name='户口地市'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='ResidenceCounty',
            field=models.CharField(max_length=100, verbose_name='户口县市'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='ResidenceProvince',
            field=models.CharField(max_length=100, verbose_name='户口省份'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='SAPNum',
            field=models.CharField(max_length=50, verbose_name='SAP员工'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='School',
            field=models.CharField(max_length=20, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Sex',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Status',
            field=models.CharField(max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Whereabouts',
            field=models.CharField(max_length=50, verbose_name='离职去向'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='CNName',
            field=models.CharField(max_length=50, verbose_name='中文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='ChangeType',
            field=models.CharField(max_length=5, verbose_name='修改类型'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='Customer',
            field=models.CharField(max_length=5, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='Department',
            field=models.CharField(max_length=50, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='DepartmentCode',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='DepartmentCodeYear',
            field=models.CharField(max_length=10, verbose_name='部门代码年份'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='EditTime',
            field=models.CharField(blank=True, max_length=26, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='Editor',
            field=models.CharField(max_length=100, verbose_name='编辑者'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='EngName',
            field=models.CharField(max_length=50, verbose_name='英文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='GroupNum',
            field=models.CharField(max_length=50, verbose_name='集团员工'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='IntervalTime',
            field=models.CharField(max_length=20, verbose_name='间隔时间'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='LastPromotionData',
            field=models.DateField(null=True, verbose_name='最近一次晋升日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='Personallink',
            field=models.ForeignKey(blank=True, on_delete=True, to='PersonalInfo.PersonalInfo', verbose_name='人员信息'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='PositionNow',
            field=models.CharField(max_length=20, verbose_name='现职称'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='PositionOld',
            field=models.CharField(max_length=20, verbose_name='原职称'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='SAPNum',
            field=models.CharField(max_length=50, verbose_name='SAP员工'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='Sex',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Aalary',
            field=models.CharField(max_length=50, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='CNName',
            field=models.CharField(max_length=50, verbose_name='中文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Customer',
            field=models.CharField(max_length=20, verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Department',
            field=models.CharField(max_length=50, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='DepartmentCode',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='ENLevel',
            field=models.CharField(max_length=500, verbose_name='英语'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Education',
            field=models.CharField(max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='EngName',
            field=models.CharField(max_length=50, verbose_name='英文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Experience',
            field=models.CharField(max_length=20, verbose_name='是否承认工作经验'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='GraduationYear',
            field=models.CharField(max_length=20, verbose_name='毕业年度'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='GroupNum',
            field=models.CharField(max_length=50, verbose_name='集团员工'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='IdCard',
            field=models.CharField(max_length=500, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='LastAchievements',
            field=models.CharField(max_length=10, verbose_name='最后一次绩效'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='LastPromotionData',
            field=models.DateField(null=True, verbose_name='最后一次晋升日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Major',
            field=models.CharField(max_length=500, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='MajorAscription',
            field=models.CharField(max_length=500, verbose_name='专业归属'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='MobileNum',
            field=models.CharField(max_length=20, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='NativeCity',
            field=models.CharField(max_length=100, verbose_name='籍贯地市'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='NativeCounty',
            field=models.CharField(max_length=100, verbose_name='籍贯县市'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='NativeProvince',
            field=models.CharField(max_length=100, verbose_name='籍贯省份'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='NewCompany',
            field=models.CharField(max_length=100, verbose_name='新公司名称'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='PlanQuitDate',
            field=models.DateField(null=True, verbose_name='预计离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Portrait',
            field=models.ForeignKey(blank=True, on_delete=True, related_name='PortraitH', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='PositionNow',
            field=models.CharField(max_length=20, verbose_name='现职称'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='PositionTimes',
            field=models.CharField(max_length=20, verbose_name='晋升次数'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='QuitDate',
            field=models.DateField(null=True, verbose_name='离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='QuitDetail',
            field=models.CharField(max_length=1000, verbose_name='离职详情'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='QuitReason',
            field=models.CharField(max_length=100, verbose_name='离职原因'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='RegistPosition',
            field=models.CharField(max_length=20, verbose_name='入职职称'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='RegistrationDate',
            field=models.DateField(null=True, verbose_name='报道日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='ResidenceCity',
            field=models.CharField(max_length=100, verbose_name='户口地市'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='ResidenceCounty',
            field=models.CharField(max_length=100, verbose_name='户口县市'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='ResidenceProvince',
            field=models.CharField(max_length=100, verbose_name='户口省份'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='SAPNum',
            field=models.CharField(max_length=50, verbose_name='SAP员工'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='School',
            field=models.CharField(max_length=20, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Sex',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Status',
            field=models.CharField(max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Whereabouts',
            field=models.CharField(max_length=50, verbose_name='离职去向'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Year',
            field=models.CharField(max_length=100, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='Grade',
            field=models.CharField(max_length=10, verbose_name='职等'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='Item',
            field=models.CharField(max_length=100, verbose_name='项次'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='Nationality',
            field=models.CharField(max_length=10, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='Positions_Code',
            field=models.CharField(max_length=50, verbose_name='职称代码'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='Positions_Name',
            field=models.CharField(max_length=50, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='CNName',
            field=models.CharField(max_length=50, verbose_name='中文姓名'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Classes',
            field=models.CharField(max_length=20, verbose_name='班别'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Department_Code',
            field=models.CharField(max_length=50, verbose_name='部门代码'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Department_Des',
            field=models.CharField(max_length=20, verbose_name='部门描述'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='GroupNum',
            field=models.CharField(max_length=50, verbose_name='集团员工'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Mounth',
            field=models.CharField(max_length=10, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='NationalHoliday',
            field=models.CharField(max_length=10, verbose_name='国假加班'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Peacetime',
            field=models.CharField(max_length=10, verbose_name='平时加班'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='PerNature',
            field=models.CharField(max_length=20, verbose_name='人员性质'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='PeriodHoliday',
            field=models.CharField(max_length=10, verbose_name='例假加班'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='RegistDate',
            field=models.CharField(max_length=20, verbose_name='报道日期'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='SalaryRange',
            field=models.CharField(max_length=20, verbose_name='计薪区间'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Total',
            field=models.CharField(max_length=10, verbose_name='总计'),
        ),
        migrations.AlterField(
            model_name='workovertime',
            name='Year',
            field=models.CharField(max_length=10, verbose_name='年份'),
        ),
    ]
