# Generated by Django 2.1.7 on 2020-12-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0003_auto_20201221_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='BU',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Companys',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司別'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='KE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Plants',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='厂区'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Apr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apr'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Aug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Aug'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='BU',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Companys',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='公司别'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Dec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Feb',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Feb'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Jan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jan'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Jul',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jul'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Jun',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Jun'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='KE',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='课'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Mar',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mar'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='May',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Nov',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nov'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Oct',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Oct'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Plants',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='厂区'),
        ),
        migrations.AlterField(
            model_name='mainpower',
            name='Sep',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sep'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Aalary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='ENLevel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='英语'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='LastAchievements',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最后一次绩效'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='LastPromotionData',
            field=models.DateField(blank=True, null=True, verbose_name='最后一次晋升日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='NewCompany',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新公司名称'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='PlanQuitDate',
            field=models.DateField(blank=True, null=True, verbose_name='预计离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='QuitDate',
            field=models.DateField(blank=True, null=True, verbose_name='离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='QuitDetail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='离职详情'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='QuitReason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='离职原因'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='RegistrationDate',
            field=models.DateField(blank=True, null=True, verbose_name='报道日期'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='SAPNum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SAP员工'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='Whereabouts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='离职去向'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='EditTime',
            field=models.CharField(max_length=26, verbose_name='编辑时间'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyper',
            name='LastPromotionData',
            field=models.DateField(blank=True, null=True, verbose_name='最近一次晋升日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Aalary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='薪资'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='CNName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中文姓名'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='ENLevel',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='英语'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='LastAchievements',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最后一次绩效'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='NewCompany',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='新公司名称'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='PlanQuitDate',
            field=models.DateField(blank=True, null=True, verbose_name='预计离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='QuitDate',
            field=models.DateField(blank=True, null=True, verbose_name='离职日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='QuitDetail',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='离职详情'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='QuitReason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='离职原因'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='RegistrationDate',
            field=models.DateField(blank=True, null=True, verbose_name='报道日期'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Whereabouts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='离职去向'),
        ),
    ]
