# Generated by Django 2.1.7 on 2023-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0003_auto_20230503_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='OldCustomer',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='原客户'),
        ),
        migrations.AddField(
            model_name='personalinfohisbyyear',
            name='OldCustomer',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='原客户'),
        ),
    ]
