# Generated by Django 2.1.7 on 2020-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0004_auto_20201230_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='Year',
            field=models.CharField(default='', max_length=100, verbose_name='年份'),
        ),
    ]
