# Generated by Django 2.1.7 on 2023-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0004_auto_20230503_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='OldDepartmentCode',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='原部门代码'),
        ),
        migrations.AddField(
            model_name='personalinfohisbyyear',
            name='OldDepartmentCode',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='原部门代码'),
        ),
    ]
