# Generated by Django 2.1.7 on 2021-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0005_positions_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='LastPromotionData',
            field=models.DateField(blank=True, null=True, verbose_name='最近一次晋升日期'),
        ),
    ]
