# Generated by Django 2.1.7 on 2021-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0006_auto_20210105_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='Portrait', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
    ]
