# Generated by Django 2.1.7 on 2021-01-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0007_auto_20210105_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Portrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='PortraitH', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
    ]
