# Generated by Django 2.1.7 on 2021-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0008_auto_20210105_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='Portrait',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='Portrait',
            field=models.ManyToManyField(blank=True, null=True, related_name='Portrait', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
        migrations.RemoveField(
            model_name='personalinfohisbyyear',
            name='Portrait',
        ),
        migrations.AddField(
            model_name='personalinfohisbyyear',
            name='Portrait',
            field=models.ManyToManyField(blank=True, null=True, related_name='PortraitH', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
    ]
