# Generated by Django 2.1.7 on 2021-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalInfo', '0009_auto_20210106_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='Portrait',
            field=models.ManyToManyField(blank=True, related_name='Portrait', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='personalinfohisbyyear',
            name='Portrait',
            field=models.ManyToManyField(blank=True, related_name='PortraitH', to='PersonalInfo.Portraits', verbose_name='头像'),
        ),
    ]
