# Generated by Django 2.1.7 on 2023-02-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Customer',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
