# Generated by Django 2.1.7 on 2021-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_cnname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Tel',
            field=models.CharField(default='', max_length=32),
        ),
    ]
