# Generated by Django 2.1.7 on 2021-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210318_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Seat',
            field=models.CharField(blank=True, default='', max_length=108, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Tel',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
