# Generated by Django 2.1.7 on 2021-03-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210318_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Seat',
            field=models.CharField(default='KS-Plant5', max_length=108),
        ),
    ]
