# Generated by Django 2.1.7 on 2021-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210318_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='Seat',
            field=models.CharField(choices=[('KS-Plant5', 'KS-Plant5'), ('CQ', 'CQ'), ('CD', 'CD')], default='KS-Plant5', max_length=108),
        ),
    ]
