# Generated by Django 2.1.7 on 2020-03-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQM', '0002_auto_20200317_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqm',
            name='Category',
            field=models.CharField(default='', max_length=200, verbose_name='Catefory'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_DQA_Compatibility',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_DQA_Compatibility'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_DQA_DataCode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='INV_DQA_DataCode'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_DQA_Reliability',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_DQA_Reliability'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_DQA_Result',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_DQA_Result'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_1',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_1'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_2',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_2'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_3',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_3'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_4',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_4'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_5',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_5'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_EMI',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_EMI'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_ESD',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_ESD'),
        ),
        migrations.AddField(
            model_name='mqm',
            name='INV_RD_RF',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_RF'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='Name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
