# Generated by Django 2.1.7 on 2023-01-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQM', '0002_auto_20220609_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqm',
            name='B_DQA_Compatibility',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_DQA_Compatibility'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_DQA_Reliability',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_DQA_Reliability'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_DQA_Result',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_DQA_Result'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_1',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_1'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_2',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_2'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_3',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_3'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_4',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_4'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_5',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_5'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_EMI',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_EMI'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_ESD',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_ESD'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='B_RD_RF',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='B_RD_RF'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_DQA_Compatibility',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_DQA_Compatibility'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_DQA_Reliability',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_DQA_Reliability'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_DQA_Result',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_DQA_Result'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_1',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_1'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_2',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_2'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_3',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_3'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_4',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_4'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_5',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_5'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_EMI',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_EMI'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_ESD',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_ESD'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='C_RD_RF',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='C_RD_RF'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_DQA_Compatibility',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_DQA_Compatibility'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_DQA_Reliability',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_DQA_Reliability'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_DQA_Result',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_DQA_Result'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_1',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_1'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_2',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_2'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_3',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_3'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_4',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_4'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_5',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_5'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_EMI',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_EMI'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_ESD',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_ESD'),
        ),
        migrations.AlterField(
            model_name='mqm',
            name='INV_RD_RF',
            field=models.CharField(blank=True, choices=[('', ''), ('QS', 'QS'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('QT', 'QT'), ('QF', 'QF'), ('QF_L', 'QF_L'), ('DisQ', 'DisQ'), ('Drop', 'Drop'), ('Not Build', 'Not Build')], default='', max_length=10, null=True, verbose_name='INV_RD_RF'),
        ),
    ]
