# Generated by Django 2.1.7 on 2023-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MQM', '0003_auto_20230131_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqm',
            name='Name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
