# Generated by Django 2.1.7 on 2020-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_Notes_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('Project_Code', models.CharField(max_length=50, verbose_name='Project_Code')),
                ('Platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('TDMS_NO', models.CharField(max_length=50, verbose_name='TDMS_NO')),
                ('Issue_Title', models.CharField(max_length=1000, verbose_name='Issue_Title')),
                ('Root_Cause', models.CharField(max_length=2000, verbose_name='Root_Cause')),
                ('Solution', models.CharField(max_length=2000, verbose_name='Solution')),
                ('PL', models.CharField(max_length=20, verbose_name='PL')),
                ('Editor', models.CharField(max_length=20, verbose_name='Editor')),
                ('Edittime', models.DateTimeField(max_length=20, verbose_name='Edittime')),
            ],
        ),
    ]
