# Generated by Django 2.1.7 on 2020-10-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Issue_Notes', '0003_auto_20201019_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue_notes_m',
            name='测试',
        ),
    ]
