# Generated by Django 2.1.7 on 2020-12-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issue_Notes', '0004_remove_issue_notes_m_测试'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_notes_m',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
    ]
