# Generated by Django 2.1.7 on 2024-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0028_auto_20240628_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='A32files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='videos/A32/Lesson/', verbose_name='视频内容')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频名称')),
            ],
        ),
        migrations.CreateModel(
            name='A32Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/A32/Lesson/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.CreateModel(
            name='A32lesson_learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('', ''), ('Reliability', 'Reliability'), ('Compatibility', 'Compatibility')], default='Reliability', max_length=100)),
                ('Object', models.CharField(max_length=100)),
                ('Symptom', models.CharField(max_length=1000)),
                ('Reproduce_Steps', models.CharField(blank=True, default='', max_length=2000, verbose_name='Reproduce_Steps')),
                ('Root_Cause', models.CharField(max_length=2000, verbose_name='Root_Cause')),
                ('Solution', models.CharField(max_length=2000, verbose_name='Solution')),
                ('Action', models.CharField(blank=True, default='', max_length=2000, verbose_name='Action')),
                ('Status', models.CharField(blank=True, choices=[('', ''), ('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20, verbose_name='Status')),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(blank=True, max_length=26, verbose_name='edit_time')),
                ('Photo', models.ManyToManyField(blank=True, related_name='imgs', to='A32LessonLProject.A32Imgs', verbose_name='图片表')),
                ('video', models.ManyToManyField(blank=True, related_name='video', to='A32LessonLProject.A32files', verbose_name='视频表')),
            ],
            options={
                'verbose_name': 'A32lesson_learn',
                'verbose_name_plural': 'A32lesson_learn',
            },
        ),
        migrations.CreateModel(
            name='A32lessonlearn_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('', ''), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/S', 'N/S'), ('N/A', 'N/A'), ('N/P', 'N/P')], max_length=20)),
                ('Comment', models.CharField(max_length=1000)),
                ('editor', models.CharField(default='', max_length=100)),
                ('edit_time', models.CharField(blank=True, default='', max_length=26, verbose_name='edit_time')),
            ],
        ),
        migrations.CreateModel(
            name='A32TestProjectLL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('A32', 'A32'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('Project', models.CharField(max_length=20, unique=True, verbose_name='Project')),
                ('Owner', models.ManyToManyField(to='app01.UserInfo')),
            ],
            options={
                'verbose_name': 'A32TestProjectLL',
                'verbose_name_plural': 'A32TestProjectLL',
            },
        ),
        migrations.AddField(
            model_name='a32lessonlearn_project',
            name='Projectinfo',
            field=models.ForeignKey(on_delete=True, to='A32LessonLProject.A32TestProjectLL'),
        ),
        migrations.AddField(
            model_name='a32lessonlearn_project',
            name='lesson',
            field=models.ForeignKey(on_delete=True, to='A32LessonLProject.A32lesson_learn'),
        ),
    ]
