# Generated by Django 2.1.7 on 2021-12-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerLNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=16, unique=True, verbose_name='統一編號')),
                ('MaterialPN', models.CharField(blank=True, max_length=128, null=True, verbose_name='MaterialPN')),
                ('CPU', models.CharField(max_length=64, verbose_name='CPU')),
                ('RAM', models.CharField(max_length=512, verbose_name='RAM')),
                ('HDD', models.CharField(max_length=256, verbose_name='HDD')),
                ('Wireless', models.CharField(max_length=8, verbose_name='Wireless')),
                ('LCD', models.CharField(max_length=128, verbose_name='LCD')),
                ('OCR', models.CharField(max_length=128, verbose_name='OCR')),
                ('Battery', models.CharField(max_length=8, verbose_name='Battery')),
                ('Adaptor', models.CharField(max_length=8, verbose_name='Adaptor')),
                ('Area', models.CharField(max_length=8, verbose_name='地區')),
                ('Carryif', models.CharField(max_length=64, verbose_name='攜出廠外')),
                ('Plant', models.CharField(max_length=8, verbose_name='廠區')),
                ('Purpose', models.CharField(max_length=256, verbose_name='電腦用途')),
                ('Category', models.CharField(max_length=64, verbose_name='產品類別')),
                ('BrwStatus', models.CharField(blank=True, choices=[('使用中', '使用中'), ('申請中', '申請中'), ('歸還中', '歸還中'), ('轉帳中', '轉帳中'), ('接收中', '接收中'), ('閑置中', '閑置中'), ('已報廢', '已報廢'), ('申請確認中', '申請確認中'), ('歸還確認中', '歸還確認中'), ('轉帳確認中', '轉帳確認中')], max_length=64, null=True, verbose_name='工作機狀態')),
                ('IdleStatus', models.CharField(blank=True, choices=[('待轉賬', '待轉賬'), ('待退庫', '待退庫')], max_length=64, null=True, verbose_name='閒置狀態')),
                ('EFormNo', models.CharField(max_length=64, verbose_name='E-Form單號')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='姓名')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='工號')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='領用日期')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Last_BR_per', models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任使用人姓名')),
                ('Last_BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任使用人工號')),
                ('Last_Borrow_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='上一次領用日期')),
                ('Last_Return_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='上一次歸還日期')),
                ('Receive_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='接收人員工號')),
                ('Sign_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='簽核人員工號')),
            ],
            options={
                'verbose_name': 'ComputerLNV',
                'verbose_name_plural': 'ComputerLNV',
            },
        ),
        migrations.CreateModel(
            name='ComputerLNVHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=16, verbose_name='統一編號')),
                ('EFormNo', models.CharField(max_length=64, verbose_name='E-Form單號')),
                ('Carryif', models.CharField(max_length=64, verbose_name='攜出廠外')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='姓名')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='工號')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='領用日期')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'NB借还记录',
                'verbose_name_plural': 'NB借还记录',
            },
        ),
    ]
