# Generated by Django 2.1.7 on 2022-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerMS', '0002_auto_20220117_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlnv',
            name='Transefer_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號'),
        ),
        migrations.AlterField(
            model_name='computerlnv',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已報廢', '已報廢'), ('申請確認中', '申請確認中'), ('歸還確認中', '歸還確認中'), ('轉帳確認中', '轉帳確認中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='工作機狀態'),
        ),
    ]
