# Generated by Django 2.1.7 on 2022-02-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerMS', '0003_auto_20220210_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlnvhis',
            name='Receive_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='接收人員工號'),
        ),
        migrations.AddField(
            model_name='computerlnvhis',
            name='Transefer_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號'),
        ),
    ]
