# Generated by Django 2.1.7 on 2022-03-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerMS', '0004_auto_20220215_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerlnv',
            name='linshi_BrwStatus',
            field=models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已報廢', '已報廢'), ('申請確認中', '申請確認中'), ('歸還確認中', '歸還確認中'), ('轉帳確認中', '轉帳確認中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='临时工作機狀態'),
        ),
    ]
