# Generated by Django 2.1.7 on 2021-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterPowerCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Changjia', models.CharField(max_length=108, verbose_name='廠家')),
                ('MaterialPN', models.CharField(max_length=108, verbose_name='MaterialPN')),
                ('Description', models.CharField(max_length=1000, verbose_name='Description')),
                ('Power', models.CharField(max_length=64, verbose_name='功率')),
                ('Number', models.CharField(max_length=64, verbose_name='編號')),
                ('Location', models.CharField(max_length=64, verbose_name='Location')),
                ('Customer', models.CharField(max_length=64, verbose_name='客戶別')),
                ('Project_Code', models.CharField(max_length=16, verbose_name='ProjectCode')),
                ('Phase', models.CharField(max_length=16, verbose_name='Phase')),
                ('OAP', models.CharField(max_length=16, verbose_name='掛賬人')),
                ('Device_Status', models.CharField(max_length=64, verbose_name='設備狀態')),
                ('BR_Status', models.CharField(max_length=64, verbose_name='借還狀態')),
                ('BR_per', models.CharField(max_length=64, verbose_name='借還人員')),
                ('Predict_return', models.DateField(max_length=64, verbose_name='預計歸還日期')),
                ('Borrow_date', models.DateField(max_length=64, verbose_name='借用日期')),
                ('Return_date', models.DateField(max_length=64, verbose_name='歸還日期')),
                ('Last_BR_per', models.CharField(max_length=64, verbose_name='最近一次借還人員')),
                ('Last_Borrow_date', models.DateField(max_length=64, verbose_name='最近一次借用日期')),
                ('Last_Return_date', models.DateField(max_length=64, verbose_name='最近一次歸還日期')),
            ],
        ),
        migrations.CreateModel(
            name='PICS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='Adapter/PIC/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.AddField(
            model_name='adapterpowercode',
            name='Photo',
            field=models.ManyToManyField(blank=True, related_name='pics', to='AdapterPowerCode.PICS', verbose_name='图片表'),
        ),
    ]
