# Generated by Django 2.1.7 on 2023-02-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdapterPowerCodeBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Changjia', models.CharField(max_length=108, verbose_name='廠家')),
                ('MaterialPN', models.CharField(max_length=108, verbose_name='MaterialPN')),
                ('Description', models.CharField(max_length=1000, verbose_name='Description')),
                ('Power', models.CharField(max_length=64, verbose_name='功率')),
                ('Number', models.CharField(max_length=64, unique=True, verbose_name='編號')),
                ('Model', models.CharField(blank=True, max_length=256, null=True, verbose_name='Model')),
                ('Pinming', models.CharField(blank=True, choices=[('PowerCode', 'PowerCode'), ('Adapter', 'Adapter')], max_length=64, null=True, verbose_name='品名')),
                ('Leibie', models.CharField(blank=True, choices=[('一類', '一類'), ('二類', '二類')], max_length=64, null=True, verbose_name='類別')),
                ('Location', models.CharField(max_length=64, verbose_name='Location')),
                ('Customer', models.CharField(max_length=64, verbose_name='客戶別')),
                ('OAP', models.CharField(blank=True, max_length=16, null=True, verbose_name='掛賬人')),
                ('OAPcode', models.CharField(blank=True, max_length=16, null=True, verbose_name='掛賬人工號')),
                ('Project_Code', models.CharField(max_length=16, verbose_name='ProjectCode')),
                ('Phase', models.CharField(max_length=16, verbose_name='Phase')),
                ('Device_Status', models.CharField(blank=True, max_length=64, null=True, verbose_name='設備狀態')),
                ('BR_Status', models.CharField(blank=True, choices=[('已借出', '已借出'), ('可借用', '可借用'), ('預定確認', '預定確認'), ('歸還確認', '歸還確認'), ('續借確認', '續借確認'), ('Close', 'Close')], max_length=64, null=True, verbose_name='借還狀態')),
                ('BR_per', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員工號')),
                ('Predict_return', models.DateField(blank=True, max_length=64, null=True, verbose_name='預計歸還日期')),
                ('Borrow_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='借用日期')),
                ('Return_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Last_BR_per', models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員')),
                ('Last_BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員工號')),
                ('Last_Predict_return', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次預計歸還日期')),
                ('Last_Borrow_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次借用日期')),
                ('Last_Return_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次歸還日期')),
            ],
        ),
        migrations.CreateModel(
            name='PICS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='Adapter/PIC/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.AddField(
            model_name='adapterpowercodebr',
            name='Photo',
            field=models.ManyToManyField(blank=True, related_name='pics', to='AdapterPowerCode.PICS', verbose_name='图片表'),
        ),
    ]
