# Generated by Django 2.1.7 on 2021-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterpowercode',
            name='BR_Status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='借還狀態'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='BR_per',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Borrow_date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='借用日期'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Device_Status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='設備狀態'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Last_BR_per',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Last_Borrow_date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次借用日期'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Last_Return_date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次歸還日期'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Predict_return',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='預計歸還日期'),
        ),
        migrations.AlterField(
            model_name='adapterpowercode',
            name='Return_date',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期'),
        ),
    ]
