# Generated by Django 2.1.7 on 2021-03-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0003_auto_20210226_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterpowercode',
            name='BR_Status',
            field=models.CharField(blank=True, choices=[('已借出', '已借出'), ('可借用', '可借用'), ('預定確認', '預定確認'), ('歸還確認', '歸還確認'), ('續借確認', '續借確認')], max_length=64, null=True, verbose_name='借還狀態'),
        ),
    ]
