# Generated by Django 2.1.7 on 2021-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0004_auto_20210301_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapterpowercode',
            name='Last_Predict_return',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='最近一次預計歸還日期'),
        ),
    ]
