# Generated by Django 2.1.7 on 2021-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0005_adapterpowercode_last_predict_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapterpowercode',
            name='BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員工號'),
        ),
    ]
