# Generated by Django 2.1.7 on 2021-03-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0006_adapterpowercode_br_per_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapterpowercode',
            name='Last_BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='最近一次借還人員工號'),
        ),
    ]
