# Generated by Django 2.1.7 on 2021-03-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0007_adapterpowercode_last_br_per_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdapterPowerCode',
            new_name='AdapterPowerCodeBR',
        ),
    ]
