# Generated by Django 2.1.7 on 2021-04-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0008_auto_20210310_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='adapterpowercodebr',
            name='Leibie',
            field=models.CharField(blank=True, choices=[('一類', '一類'), ('二類', '二類')], max_length=64, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='adapterpowercodebr',
            name='Model',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='adapterpowercodebr',
            name='Pinming',
            field=models.CharField(blank=True, choices=[('PowerCode', 'PowerCode'), ('Adapter', 'Adapter')], max_length=64, null=True, verbose_name='品名'),
        ),
    ]
