# Generated by Django 2.1.7 on 2021-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdapterPowerCode', '0010_auto_20210401_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adapterpowercodebr',
            name='Leibie',
            field=models.CharField(blank=True, choices=[('一類', '一類'), ('二類', '二類')], max_length=64, null=True, verbose_name='類別'),
        ),
    ]
