# Generated by Django 2.1.7 on 2024-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanYear', models.CharField(default='', max_length=12, verbose_name='PlanYear')),
                ('BudgetCode', models.CharField(max_length=30, verbose_name='預算編號')),
                ('Investment_Nature', models.CharField(max_length=12, verbose_name='投資性質')),
                ('Attribute_Code', models.CharField(max_length=20, verbose_name='屬性代碼')),
                ('Application_Department', models.CharField(max_length=20, verbose_name='申請部門')),
                ('Device_Name', models.CharField(max_length=400, verbose_name='設備或工程名稱')),
                ('Usage_Description', models.CharField(max_length=2000, verbose_name='用途說明')),
                ('Specifications', models.CharField(max_length=1000, verbose_name='廠牌規格')),
                ('Acceptance_Month', models.CharField(max_length=10, verbose_name='驗收月份')),
                ('Budget_Quantity', models.IntegerField(max_length=20, verbose_name='預算數量')),
                ('Estimated_Original_Currency', models.CharField(max_length=20, verbose_name='預估總價_原幣_幣別')),
                ('Estimated_Original_Price', models.CharField(max_length=20, verbose_name='預估總價_原幣_金額')),
                ('Equivalent_To_RMB', models.IntegerField(max_length=20, verbose_name='折合人民幣')),
                ('Payment_Terms', models.CharField(max_length=200, verbose_name='付款條件')),
                ('Depreciation_Months', models.IntegerField(max_length=20, verbose_name='折舊月數')),
                ('Accounting_Subjects', models.CharField(max_length=20, verbose_name='會計科目')),
                ('Automated_Or_Not', models.CharField(max_length=20, verbose_name='是否自動化')),
                ('Project_Code', models.CharField(max_length=20, verbose_name='Project Code')),
                ('Current_Situation', models.CharField(max_length=20, verbose_name='現狀說明')),
                ('Applicable_Scope', models.CharField(max_length=20, verbose_name='適用範圍')),
                ('Investment_Purpose', models.CharField(max_length=1000, verbose_name='投資動機與目的')),
                ('Investment_Purpose_Des', models.CharField(max_length=1000, verbose_name='投資動機與目的其他說明')),
                ('Potential_Issues', models.CharField(max_length=1000, verbose_name='潛在問題')),
                ('Potential_Issues_Des', models.CharField(max_length=1000, verbose_name='潛在問題的其他說明')),
                ('Tighten_Expenses', models.CharField(max_length=20, verbose_name='年節省支出')),
                ('Annual_Increase_PerYear', models.IntegerField(max_length=20, verbose_name='年增加收益')),
                ('Investment_Benefits_PerYear', models.IntegerField(max_length=20, verbose_name='年投資效益')),
                ('Cash_Inflows_PerYear', models.IntegerField(max_length=20, verbose_name='年淨現金流入')),
                ('Payback_Period', models.IntegerField(max_length=20, verbose_name='回收年限(月數)')),
                ('Subscription_Status', models.CharField(max_length=20, verbose_name='申購狀況')),
                ('Subscription_Quantity', models.IntegerField(max_length=20, verbose_name='申購數量')),
                ('Subscription_Amount', models.FloatField(max_length=20, verbose_name='申購金額\n(CNY)')),
                ('Entry_Amount', models.FloatField(max_length=20, verbose_name='入賬金額\n(CNY)')),
            ],
            options={
                'verbose_name': 'CapitalExpenditure',
                'verbose_name_plural': 'CapitalExpenditure',
            },
        ),
    ]
