# Generated by Django 2.1.7 on 2024-05-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapitalExpenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Annual_Increase_PerYear',
            field=models.IntegerField(verbose_name='年增加收益'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Budget_Quantity',
            field=models.IntegerField(verbose_name='預算數量'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Cash_Inflows_PerYear',
            field=models.IntegerField(verbose_name='年淨現金流入'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Depreciation_Months',
            field=models.IntegerField(verbose_name='折舊月數'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Equivalent_To_RMB',
            field=models.IntegerField(verbose_name='折合人民幣'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Investment_Benefits_PerYear',
            field=models.IntegerField(verbose_name='年投資效益'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Payback_Period',
            field=models.IntegerField(verbose_name='回收年限(月數)'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Subscription_Quantity',
            field=models.IntegerField(verbose_name='申購數量'),
        ),
    ]
