# Generated by Django 2.1.7 on 2024-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapitalExpenditure', '0003_capitalexpenditure_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Acceptance_Month',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='驗收月份'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Accounting_Subjects',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='會計科目'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Annual_Increase_PerYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='年增加收益'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Applicable_Scope',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='適用範圍'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Application_Department',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='申請部門'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Attribute_Code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='屬性代碼'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Automated_Or_Not',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='是否自動化'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='BudgetCode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='預算編號'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Budget_Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='預算數量'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Cash_Inflows_PerYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='年淨現金流入'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Current_Situation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='現狀說明'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Customer',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='客戶別'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Depreciation_Months',
            field=models.IntegerField(blank=True, null=True, verbose_name='折舊月數'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Device_Name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='設備或工程名稱'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Entry_Amount',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='入賬金額\n(CNY)'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Equivalent_To_RMB',
            field=models.IntegerField(blank=True, null=True, verbose_name='折合人民幣'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Estimated_Original_Currency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='預估總價_原幣_幣別'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Estimated_Original_Price',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='預估總價_原幣_金額'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Investment_Benefits_PerYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='年投資效益'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Investment_Nature',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='投資性質'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Investment_Purpose',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='投資動機與目的'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Investment_Purpose_Des',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='投資動機與目的其他說明'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Payback_Period',
            field=models.IntegerField(blank=True, null=True, verbose_name='回收年限(月數)'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Payment_Terms',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='付款條件'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Potential_Issues',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='潛在問題'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Potential_Issues_Des',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='潛在問題的其他說明'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Project_Code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Specifications',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='廠牌規格'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Subscription_Amount',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='申購金額\n(CNY)'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Subscription_Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='申購數量'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Tighten_Expenses',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='年節省支出'),
        ),
        migrations.AlterField(
            model_name='capitalexpenditure',
            name='Usage_Description',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='用途說明'),
        ),
    ]
