# Generated by Django 2.1.7 on 2020-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVGantt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invgantt',
            name='Test_End',
            field=models.DateField(null=True, verbose_name='Test_End'),
        ),
        migrations.AlterField(
            model_name='invgantt',
            name='Test_Start',
            field=models.DateField(null=True, verbose_name='Test_Start'),
        ),
    ]
