# Generated by Django 2.1.7 on 2020-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVGantt', '0002_auto_20201009_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='invgantt',
            name='Unit_Origin',
            field=models.CharField(choices=[('', ''), ('Self', 'Self'), ('New', 'New')], default='', max_length=100, verbose_name='Unit_Origin'),
        ),
    ]
