# Generated by Django 2.1.7 on 2023-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVGantt', '0004_auto_20201223_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invgantt',
            name='Compal_TP_PN',
            field=models.CharField(max_length=200, verbose_name='Compal_TP_PN'),
        ),
    ]
