# Generated by Django 2.1.7 on 2023-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVGantt', '0005_auto_20230829_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invgantt',
            name='Get_INV',
        ),
        migrations.AddField(
            model_name='invgantt',
            name='ReTest_Attend_Time',
            field=models.CharField(default='', max_length=100, verbose_name='ReTest_Attend_Time'),
        ),
        migrations.AddField(
            model_name='invgantt',
            name='TestOwner',
            field=models.CharField(default='', max_length=100, verbose_name='TestOwner'),
        ),
    ]
