# Generated by Django 2.1.7 on 2020-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files_PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_P/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.CreateModel(
            name='Package_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=20)),
                ('Project', models.CharField(max_length=20)),
                ('Phase', models.CharField(max_length=20)),
                ('Degree', models.FloatField()),
                ('Duan', models.FloatField()),
                ('Zhong', models.FloatField()),
                ('Chang', models.FloatField()),
                ('Left', models.FloatField()),
                ('Right', models.FloatField()),
                ('Top', models.FloatField()),
                ('Bottom', models.FloatField()),
                ('Zheng', models.FloatField()),
                ('Fan', models.FloatField()),
                ('Pattern', models.CharField(max_length=30)),
                ('Conclusion', models.CharField(max_length=1000)),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
                ('files_P', models.ManyToManyField(blank=True, related_name='files_P', to='Package.files_PM', verbose_name='图文件表')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Package',
            },
        ),
    ]
