# Generated by Django 2.1.7 on 2019-09-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=20)),
                ('Project', models.CharField(max_length=20)),
                ('Phase', models.CharField(max_length=20)),
                ('Degree', models.FloatField()),
                ('Duan', models.FloatField()),
                ('Zhong', models.FloatField()),
                ('Chang', models.FloatField()),
                ('Left', models.FloatField()),
                ('Right', models.FloatField()),
                ('Top', models.FloatField()),
                ('Bottom', models.FloatField()),
                ('Zheng', models.FloatField()),
                ('Fan', models.FloatField()),
                ('Conclusion', models.CharField(max_length=1000)),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
            ],
        ),
    ]
