# Generated by Django 2.1.7 on 2019-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_m',
            name='Pattern',
            field=models.CharField(default='2', max_length=30),
        ),
    ]
