# Generated by Django 2.1.7 on 2019-10-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0002_package_m_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_m',
            name='Pattern',
            field=models.CharField(default='', max_length=30),
        ),
    ]
