# Generated by Django 2.1.7 on 2019-10-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0004_auto_20191008_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package_m',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Package'},
        ),
    ]
