# Generated by Django 2.1.7 on 2019-10-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0005_auto_20191015_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/test/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=20, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.AddField(
            model_name='package_m',
            name='Photo_P',
            field=models.ManyToManyField(blank=True, related_name='imgs_p', to='Package.Imgs_P', verbose_name='图片表'),
        ),
    ]
