# Generated by Django 2.1.7 on 2019-10-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0006_auto_20191028_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='files_PM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_P/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=20, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='package_m',
            name='Photo_P',
        ),
        migrations.DeleteModel(
            name='Imgs_P',
        ),
        migrations.AddField(
            model_name='package_m',
            name='files_P',
            field=models.ManyToManyField(blank=True, related_name='files_P', to='Package.files_PM', verbose_name='图文件表'),
        ),
    ]
