# Generated by Django 2.1.7 on 2019-11-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0007_auto_20191029_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_pm',
            name='single',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称'),
        ),
    ]
