# Generated by Django 2.1.7 on 2023-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unitbudget_C38C85',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=30, verbose_name='年份')),
                ('Jan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jan')),
                ('Feb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feb')),
                ('Mar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mar')),
                ('Apr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apr')),
                ('May', models.CharField(blank=True, max_length=50, null=True, verbose_name='May')),
                ('Jun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jun')),
                ('Jul', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jul')),
                ('Aug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aug')),
                ('Sep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sep')),
                ('Oct', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oct')),
                ('Nov', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nov')),
                ('Dec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dec')),
            ],
        ),
        migrations.CreateModel(
            name='Unitbudget_T88AIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=30, verbose_name='年份')),
                ('Jan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jan')),
                ('Feb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feb')),
                ('Mar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mar')),
                ('Apr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apr')),
                ('May', models.CharField(blank=True, max_length=50, null=True, verbose_name='May')),
                ('Jun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jun')),
                ('Jul', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jul')),
                ('Aug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aug')),
                ('Sep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sep')),
                ('Oct', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oct')),
                ('Nov', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nov')),
                ('Dec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dec')),
            ],
        ),
    ]
