# Generated by Django 2.1.7 on 2023-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0002_unitbudget_c38c85_unitbudget_t88aio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unitbudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('C85', 'C85'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39')], max_length=30, verbose_name='Customer')),
                ('Year', models.CharField(max_length=30, verbose_name='年份')),
                ('Jan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jan')),
                ('Feb', models.CharField(blank=True, max_length=50, null=True, verbose_name='Feb')),
                ('Mar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mar')),
                ('Apr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apr')),
                ('May', models.CharField(blank=True, max_length=50, null=True, verbose_name='May')),
                ('Jun', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jun')),
                ('Jul', models.CharField(blank=True, max_length=50, null=True, verbose_name='Jul')),
                ('Aug', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aug')),
                ('Sep', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sep')),
                ('Oct', models.CharField(blank=True, max_length=50, null=True, verbose_name='Oct')),
                ('Nov', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nov')),
                ('Dec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dec')),
            ],
        ),
        migrations.DeleteModel(
            name='Unitbudget_C38C85',
        ),
        migrations.DeleteModel(
            name='Unitbudget_T88AIO',
        ),
    ]
