# Generated by Django 2.1.7 on 2023-09-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0003_auto_20230925_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqamateria_tumhistory',
            name='ReturnData',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='退庫日期'),
        ),
        migrations.AlterField(
            model_name='dqaunit_tumhistory',
            name='ReturnData',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='退庫日期'),
        ),
        migrations.AlterField(
            model_name='materiaindqa_tum',
            name='ReturnData',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='退庫日期'),
        ),
        migrations.AlterField(
            model_name='unitindqa_tum',
            name='ReturnData',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='退庫日期'),
        ),
    ]
