# Generated by Django 2.1.7 on 2023-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0004_auto_20230925_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqamateria_tumhistory',
            name='ApplyReason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='領用原因'),
        ),
        migrations.AlterField(
            model_name='dqamateria_tumhistory',
            name='Description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dqaunit_tumhistory',
            name='ApplyReason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='領用原因'),
        ),
        migrations.AlterField(
            model_name='dqaunit_tumhistory',
            name='Description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='materiaindqa_tum',
            name='ApplyReason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='領用原因'),
        ),
        migrations.AlterField(
            model_name='materiaindqa_tum',
            name='Description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unitindqa_tum',
            name='ApplyReason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='領用原因'),
        ),
        migrations.AlterField(
            model_name='unitindqa_tum',
            name='Description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Description'),
        ),
    ]
