# Generated by Django 2.1.7 on 2023-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0009_auto_20231009_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqamateria_tumhistory',
            name='QTY',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='dqaunit_tumhistory',
            name='QTY',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='materiaindqa_tum',
            name='QTY',
            field=models.IntegerField(blank=True, null=True, verbose_name='QTY'),
        ),
    ]
