# Generated by Django 2.1.7 on 2023-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0010_auto_20231009_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqamateria_tumhistory',
            name='ReturnOffline',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='歸還期限'),
        ),
    ]
