# Generated by Django 2.1.7 on 2023-10-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUMHistory', '0011_auto_20231009_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqamateria_tumhistory',
            name='ReturnOffline',
            field=models.DateField(blank=True, max_length=60, null=True, verbose_name='歸還期限'),
        ),
    ]
