# Generated by Django 2.1.7 on 2020-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonProjectME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testprojectll',
            name='Project',
            field=models.CharField(max_length=20, unique=True, verbose_name='Project'),
        ),
    ]
