# Generated by Django 2.1.7 on 2020-10-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LessonProjectME', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlearn_project',
            name='result',
            field=models.CharField(choices=[('', ''), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/S', 'N/S'), ('N/A', 'N/A'), ('Not Planning', 'Not Planning')], max_length=20),
        ),
    ]
