# Generated by Django 2.1.7 on 2020-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeypartAIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R')),
                ('Project', models.CharField(max_length=20, verbose_name='Project_R')),
                ('Phase', models.CharField(max_length=20, verbose_name='Phase')),
                ('IDs', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('SKU', models.CharField(blank=True, max_length=20, null=True, verbose_name='SKU')),
                ('Planar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Planar')),
                ('Panel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Panel')),
                ('Stand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stand')),
                ('Cable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cable')),
                ('Connectorsource', models.CharField(blank=True, max_length=20, null=True, verbose_name='Connectorsource')),
                ('SSDHHD', models.CharField(blank=True, max_length=20, null=True, verbose_name='SSDHHD')),
                ('Camera', models.CharField(blank=True, max_length=20, null=True, verbose_name='Camera')),
                ('ODD', models.CharField(blank=True, max_length=20, null=True, verbose_name='ODD')),
                ('Package', models.CharField(blank=True, max_length=20, null=True, verbose_name='Package')),
                ('RegularAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegularAttendTime')),
                ('RegressiveAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegressiveAttendTime')),
            ],
            options={
                'verbose_name': 'KeypartAIO',
                'verbose_name_plural': 'KeypartAIO',
            },
        ),
        migrations.CreateModel(
            name='KeypartC38NB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R')),
                ('Project', models.CharField(max_length=20, verbose_name='Project_R')),
                ('Phase', models.CharField(max_length=20, verbose_name='Phase')),
                ('IDs', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type')),
                ('SKU', models.CharField(blank=True, max_length=20, null=True, verbose_name='SKU')),
                ('Planar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Planar')),
                ('Panel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Panel')),
                ('Hinge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hinge')),
                ('Cable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cable')),
                ('Connectorsource', models.CharField(blank=True, max_length=20, null=True, verbose_name='Connectorsource')),
                ('Keyboard', models.CharField(blank=True, max_length=20, null=True, verbose_name='Keyboard')),
                ('ClickPad', models.CharField(blank=True, max_length=20, null=True, verbose_name='ClickPad')),
                ('SSDHHD', models.CharField(blank=True, max_length=20, null=True, verbose_name='SSDHHD')),
                ('Camera', models.CharField(blank=True, max_length=20, null=True, verbose_name='Camera')),
                ('Rubberfoot', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rubberfoot')),
                ('ODD', models.CharField(blank=True, max_length=20, null=True, verbose_name='ODD')),
                ('TrapDoorRJ45', models.CharField(blank=True, max_length=20, null=True, verbose_name='TrapDoorRJ45')),
                ('RegularAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegularAttendTime')),
                ('RegressiveAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegressiveAttendTime')),
            ],
            options={
                'verbose_name': 'KeypartC38NB',
                'verbose_name_plural': 'KeypartC38NB',
            },
        ),
        migrations.CreateModel(
            name='TestItemME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemNo_d', models.CharField(max_length=50, verbose_name='ItemNo')),
                ('Item_d', models.CharField(max_length=150, verbose_name='Item')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer')),
                ('Phase', models.CharField(blank=True, choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('INV', 'INV'), ('Others', 'Others')], default='', max_length=20, null=True, verbose_name='Phase')),
                ('Facility_Name_d', models.CharField(blank=True, max_length=50, null=True, verbose_name='Facility_Name')),
                ('Voltage_d', models.CharField(blank=True, max_length=15, null=True, verbose_name='Voltage')),
                ('Sample_Size_d', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sample_Size')),
                ('TimePunits_Facility_d', models.FloatField(blank=True, max_length=10, null=True, verbose_name='TimePunits_Facility')),
                ('TimePunits_Manual_d', models.FloatField(blank=True, max_length=10, null=True, verbose_name='TimePunits_Manual')),
                ('TimePunits_Program_d', models.FloatField(blank=True, max_length=10, null=True, verbose_name='TimePunits_Program')),
                ('Formula', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formula')),
            ],
            options={
                'verbose_name': 'TestItemME',
                'verbose_name_plural': 'TestItemME',
            },
        ),
        migrations.CreateModel(
            name='TestPlanME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NormalAmount', models.FloatField(blank=True, max_length=10, null=True, verbose_name='NormalAmount')),
                ('NormalFacilityTime', models.FloatField(blank=True, max_length=10, null=True, verbose_name='NormalFacilityTime')),
                ('NormalAttendTime', models.FloatField(blank=True, max_length=10, null=True, verbose_name='NormalAttendTime')),
                ('NormalProgramtime', models.FloatField(blank=True, max_length=10, null=True, verbose_name='NormalProgramtime')),
                ('RegCycles', models.FloatField(blank=True, max_length=10, null=True, verbose_name='RegCycles')),
                ('RegAmount', models.FloatField(blank=True, max_length=10, null=True, verbose_name='RegAmount')),
                ('RegFacilityTime', models.FloatField(blank=True, max_length=10, null=True, verbose_name='RegFacilityTime')),
                ('RegAttendTime', models.FloatField(blank=True, max_length=10, null=True, verbose_name='RegAttendTime')),
                ('RegProgramtime', models.FloatField(blank=True, max_length=10, null=True, verbose_name='RegProgramtime')),
                ('editor', models.CharField(default='', max_length=100)),
                ('edit_time', models.CharField(blank=True, default='', max_length=26, verbose_name='edit_time')),
                ('Items', models.ForeignKey(on_delete=True, to='TestPlanME.TestItemME')),
            ],
            options={
                'verbose_name': 'TestPlanME',
                'verbose_name_plural': 'TestPlanME',
            },
        ),
        migrations.CreateModel(
            name='TestProjectME',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('Project', models.CharField(max_length=20, verbose_name='Project')),
                ('Phase', models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('INV', 'INV'), ('Others', 'Others')], max_length=20, verbose_name='Phase')),
                ('ScheduleBegin', models.DateField(blank=True, null=True, verbose_name='ScheduleBegin')),
                ('Owner', models.ManyToManyField(to='app01.UserInfo')),
            ],
            options={
                'verbose_name': 'TestProjectME',
                'verbose_name_plural': 'TestProjectME',
            },
        ),
        migrations.AddField(
            model_name='testplanme',
            name='Projectinfo',
            field=models.ForeignKey(on_delete=True, to='TestPlanME.TestProjectME'),
        ),
    ]
