# Generated by Django 2.1.7 on 2019-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitemme',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='testitemme',
            name='Phase',
            field=models.CharField(blank=True, choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('INV', 'INV'), ('Others', 'Others')], default='', max_length=20, null=True, verbose_name='Phase'),
        ),
    ]
