# Generated by Django 2.1.7 on 2020-04-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanME', '0002_auto_20191211_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitemme',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='testitemme',
            name='ItemNo_d',
            field=models.CharField(max_length=50, verbose_name='ItemNo'),
        ),
        migrations.AlterField(
            model_name='testprojectme',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
    ]
