# Generated by Django 2.1.7 on 2020-06-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanME', '0003_auto_20200422_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeypartAIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R')),
                ('Project', models.CharField(max_length=20, verbose_name='Project_R')),
                ('Phase', models.CharField(max_length=20, verbose_name='Phase')),
                ('IDs', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('SKU', models.CharField(blank=True, max_length=20, null=True, verbose_name='SKU')),
                ('Planar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Planar')),
                ('Panel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Panel')),
                ('Stand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stand')),
                ('Cable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cable')),
                ('Connectorsource', models.CharField(blank=True, max_length=20, null=True, verbose_name='Connectorsource')),
                ('SSDHHD', models.CharField(blank=True, max_length=20, null=True, verbose_name='SSDHHD')),
                ('Camera', models.CharField(blank=True, max_length=20, null=True, verbose_name='Camera')),
                ('ODD', models.CharField(blank=True, max_length=20, null=True, verbose_name='ODD')),
                ('Package', models.CharField(blank=True, max_length=20, null=True, verbose_name='Package')),
                ('RegularAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegularAttendTime')),
                ('RegressiveAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegressiveAttendTime')),
            ],
            options={
                'verbose_name': 'KeypartAIO',
                'verbose_name_plural': 'KeypartAIO',
            },
        ),
        migrations.CreateModel(
            name='KeypartC38NB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R')),
                ('Project', models.CharField(max_length=20, verbose_name='Project_R')),
                ('Phase', models.CharField(max_length=20, verbose_name='Phase')),
                ('IDs', models.CharField(blank=True, max_length=20, null=True, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Type')),
                ('SKU', models.CharField(blank=True, max_length=20, null=True, verbose_name='SKU')),
                ('Planar', models.CharField(blank=True, max_length=20, null=True, verbose_name='Planar')),
                ('Panel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Panel')),
                ('Hinge', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hinge')),
                ('Cable', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cable')),
                ('Connectorsource', models.CharField(blank=True, max_length=20, null=True, verbose_name='Connectorsource')),
                ('Keyboard', models.CharField(blank=True, max_length=20, null=True, verbose_name='Keyboard')),
                ('ClickPad', models.CharField(blank=True, max_length=20, null=True, verbose_name='ClickPad')),
                ('SSDHHD', models.CharField(blank=True, max_length=20, null=True, verbose_name='SSDHHD')),
                ('Camera', models.CharField(blank=True, max_length=20, null=True, verbose_name='Camera')),
                ('Rubberfoot', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rubberfoot')),
                ('ODD', models.CharField(blank=True, max_length=20, null=True, verbose_name='ODD')),
                ('TrapDoorRJ45', models.CharField(blank=True, max_length=20, null=True, verbose_name='TrapDoorRJ45')),
                ('RegularAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegularAttendTime')),
                ('RegressiveAttendTime', models.CharField(blank=True, max_length=20, null=True, verbose_name='RegressiveAttendTime')),
            ],
            options={
                'verbose_name': 'KeypartC38NB',
                'verbose_name_plural': 'KeypartC38NB',
            },
        ),
        migrations.AddField(
            model_name='testprojectme',
            name='ScheduleBegin',
            field=models.DateField(blank=True, null=True, verbose_name='ScheduleBegin'),
        ),
    ]
