# Generated by Django 2.1.7 on 2023-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanME', '0005_auto_20210422_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypartaio',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('T88(AIO)', 'T88(AIO)'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R'),
        ),
        migrations.AlterField(
            model_name='keypartc38nb',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('C85', 'C85'), ('T88(AIO)', 'T88(AIO)'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R'),
        ),
        migrations.AlterField(
            model_name='testitemme',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('T88(AIO)', 'T88(AIO)'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='testprojectme',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('T88(AIO)', 'T88(AIO)'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
    ]
