# Generated by Django 2.1.7 on 2020-03-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testprojectsw',
            name='Full_Function_Duration',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Full_Function_Duration'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='Gerber',
            field=models.DateField(blank=True, null=True, verbose_name='Gerber'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='ScheduleBegin',
            field=models.DateField(blank=True, null=True, verbose_name='ScheduleBegin'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='ScheduleEnd',
            field=models.DateField(blank=True, null=True, verbose_name='ScheduleEnd'),
        ),
    ]
