# Generated by Django 2.1.7 on 2020-12-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU21',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU21_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU22',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU22_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU23',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU23_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU24',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU24_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU25',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU25_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU26',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU26_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU27',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU27_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU28',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU28_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU29',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU29_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU30',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU30_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU31',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU31_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU32',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU32_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU33',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU33_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU34',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU34_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU35',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU35_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU36',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU36_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU37',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU37_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU38',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU38_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU39',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU39_R'),
        ),
        migrations.AddField(
            model_name='retestitemsw',
            name='SKU40',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU40_R'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU21',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU21'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU22',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU22'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU23',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU23'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU24',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU24'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU25',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU25'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU26',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU26'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU27',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU27'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU28',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU28'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU29',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU29'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU30',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU30'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU31',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU31'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU32',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU32'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU33',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU33'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU34',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU34'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU35',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU35'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU36',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU36'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU37',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU37'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU38',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU38'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU39',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU39'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='SKU40',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('A', 'A'), ('L', 'L'), ('S', 'S')], default='', max_length=200, null=True, verbose_name='SKU40'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU21',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU21'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU22',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU22'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU23',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU23'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU24',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU24'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU25',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU25'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU26',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU26'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU27',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU27'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU28',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU28'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU29',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU29'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU30',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU30'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU31',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU31'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU32',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU32'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU33',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU33'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU34',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU34'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU35',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU35'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU36',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU36'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU37',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU37'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU38',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU38'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU39',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU39'),
        ),
        migrations.AddField(
            model_name='testprojectsw',
            name='SKU40',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='SKU40'),
        ),
    ]
