# Generated by Django 2.1.7 on 2020-04-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0002_auto_20200320_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplansw',
            name='BaseAotomationTime1SKU',
            field=models.FloatField(blank=True, max_length=10, null=True, verbose_name='BaseAotomationTime1SKU'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='BaseTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='BaseTime'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Category2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Category2'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Chramshell',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='Chramshell'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='ConvertibaleNBMode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='ConvertibaleNBMode'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='ConvertibaleYogaPadMode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='ConvertibaleYogaPadMode'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Coverage',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Coverage'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='DetachablePadMode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='DetachablePadMode'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='DetachableWDockmode',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='DetachableWDockmode'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='ItemNo_d',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ItemNo'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Item_d',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('FFRT', 'FFRT'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='PhaseFFRT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='PhaseFFRT'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='PhaseFVT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='PhaseFVT'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='PhaseSIT',
            field=models.CharField(blank=True, choices=[('', ''), ('V', 'V'), ('X', 'X'), ('O', 'O')], default='', max_length=10, null=True, verbose_name='PhaseSIT'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Priority',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='ReleaseDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ReleaseDate'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='TDMSTotalTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='TDMSTotalTime'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='TDMSUnattendedTime',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='TDMSUnattendedTime'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='TestItems',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='TestItems'),
        ),
        migrations.AddField(
            model_name='testplansw',
            name='Version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
    ]
