# Generated by Django 2.1.7 on 2020-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0003_auto_20200403_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFRTByRD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('C38(AIO)-T88', 'C38(AIO)-T88'), ('A39', 'A39'), ('Others', 'Others')], default='C38(NB)', max_length=20, verbose_name='Customer_R')),
                ('Project', models.CharField(max_length=20, verbose_name='Project_R')),
                ('EC', models.IntegerField(blank=True, null=True, verbose_name='EC')),
                ('RF', models.IntegerField(blank=True, null=True, verbose_name='RF')),
                ('EMI', models.IntegerField(blank=True, null=True, verbose_name='EMI')),
                ('ESD', models.IntegerField(blank=True, null=True, verbose_name='ESD')),
                ('HW', models.IntegerField(blank=True, null=True, verbose_name='HW')),
                ('SW', models.IntegerField(blank=True, null=True, verbose_name='SW')),
                ('SA', models.IntegerField(blank=True, null=True, verbose_name='SA')),
                ('SIT', models.IntegerField(blank=True, null=True, verbose_name='SIT')),
                ('Thermal', models.IntegerField(blank=True, null=True, verbose_name='Themal')),
                ('Power', models.IntegerField(blank=True, null=True, verbose_name='Power')),
                ('SED', models.IntegerField(blank=True, null=True, verbose_name='SED')),
            ],
            options={
                'verbose_name': 'FFRTByRD',
                'verbose_name_plural': 'FFRTByRD',
            },
        ),
        migrations.AlterField(
            model_name='retestitemsw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase_R'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='Items',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='TestPlanSW.TestItemSW'),
        ),
        migrations.AlterField(
            model_name='testplansw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='testprojectsw',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(FVT)', 'B(FVT)'), ('C(SIT)', 'C(SIT)'), ('SIT2', 'SIT2'), ('Wave', 'Wave'), ('Wave2', 'Wave2'), ('Wave3', 'Wave3'), ('Wave4', 'Wave4'), ('Wave5', 'Wave5'), ('OOC', 'OOC'), ('OOC2', 'OOC2'), ('OOC3', 'OOC3'), ('OOC4', 'OOC4'), ('OOC5', 'OOC5'), ('OOC6', 'OOC6'), ('FFRT', 'FFRT'), ('FFRT2', 'FFRT2'), ('FFRT3', 'FFRT3'), ('FFRT4', 'FFRT4'), ('FFRT5', 'FFRT5'), ('FFRT6', 'FFRT6'), ('Others', 'Others')], max_length=20, verbose_name='Phase'),
        ),
    ]
