# Generated by Django 2.1.7 on 2020-06-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0004_auto_20200514_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplansw',
            name='FeatureSupport',
            field=models.CharField(blank=True, choices=[('', ''), ('Y', 'Y'), ('N', 'N')], default='', max_length=5, null=True, verbose_name='FeatureSupport'),
        ),
    ]
