# Generated by Django 2.1.7 on 2020-10-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestPlanSW', '0006_auto_20200921_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplanswaio',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(SDV)', 'B(SDV)'), ('C(SIT)', 'C(SIT)'), ('EELP+', 'EELP+'), ('Others', 'Others')], default='', max_length=20, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='testprojectswaio',
            name='Phase',
            field=models.CharField(choices=[('', ''), ('B(SDV)', 'B(SDV)'), ('C(SIT)', 'C(SIT)'), ('EELP+', 'EELP+'), ('Others', 'Others')], max_length=20, verbose_name='Phase'),
        ),
    ]
