# Generated by Django 2.1.7 on 2020-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='视频内容')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频名称')),
            ],
        ),
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/test/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.CreateModel(
            name='lesson_learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('', ''), ('Reliability', 'Reliability'), ('Compatibility', 'Compatibility')], default='Reliability', max_length=100)),
                ('Object', models.CharField(max_length=100)),
                ('Symptom', models.CharField(max_length=1000)),
                ('Reproduce_Steps', models.CharField(blank=True, default='', max_length=2000, verbose_name='Reproduce_Steps')),
                ('Root_Cause', models.CharField(max_length=2000, verbose_name='Root_Cause')),
                ('Solution', models.CharField(max_length=2000, verbose_name='Solution')),
                ('Action', models.CharField(blank=True, default='', max_length=2000, verbose_name='Action')),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(blank=True, max_length=26, verbose_name='edit_time')),
                ('Photo', models.ManyToManyField(blank=True, related_name='imgs', to='app01.Imgs', verbose_name='图片表')),
                ('video', models.ManyToManyField(blank=True, related_name='video', to='app01.files', verbose_name='视频表')),
            ],
            options={
                'verbose_name': 'lesson_learnME',
                'verbose_name_plural': 'lesson_learnME',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=True, to='app01.Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu_title', models.CharField(max_length=32, unique=True)),
                ('url', models.CharField(max_length=128, unique=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=True, to='app01.Menu')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='ProjectinfoinDCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=5, verbose_name='Year')),
                ('ComPrjCode', models.CharField(max_length=10, verbose_name='ComPrjCode')),
                ('PrjEngCode1', models.CharField(default='', max_length=50, verbose_name='PrjEngCode1')),
                ('PrjEngCode2', models.CharField(default='', max_length=50, verbose_name='PrjEngCode2')),
                ('ProjectName', models.CharField(max_length=1000, verbose_name='ProjectName')),
                ('Size', models.CharField(max_length=10, verbose_name='Size')),
                ('CPU', models.CharField(max_length=50, verbose_name='CPU')),
                ('Platform', models.CharField(max_length=500, verbose_name='Platform')),
                ('VGA', models.CharField(max_length=1000, verbose_name='VGA')),
                ('OSSupport', models.CharField(max_length=500, verbose_name='OSSupport')),
                ('SS', models.CharField(max_length=30, verbose_name='SS')),
                ('LD', models.CharField(max_length=20, verbose_name='LD')),
                ('DQAPL', models.CharField(max_length=20, verbose_name='DQAPL')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('perms', models.ManyToManyField(to='app01.Permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Role',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.ManyToManyField(to='app01.Role')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
    ]
