# Generated by Django 2.1.7 on 2020-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_projectinfoindct_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfoindct',
            name='ModifiedDate',
            field=models.CharField(default='', max_length=20, verbose_name='ModifiedDate'),
        ),
    ]
