# Generated by Django 2.1.7 on 2019-10-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191015_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_learn',
            name='Action',
            field=models.CharField(default='', max_length=1000, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Root_Cause',
            field=models.CharField(max_length=1000, verbose_name='Root_Cause'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Solution',
            field=models.CharField(max_length=1000, verbose_name='Solution'),
        ),
    ]
