# Generated by Django 2.1.7 on 2019-10-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20191024_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='Object',
            field=models.CharField(max_length=100),
        ),
    ]
