# Generated by Django 2.1.7 on 2019-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20191029_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='edit_time',
            field=models.DateField(blank=True, max_length=26, verbose_name='edit_time'),
        ),
    ]
