# Generated by Django 2.1.7 on 2020-12-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20201229_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfoindct',
            name='PrjEngCode1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='PrjEngCode1'),
        ),
        migrations.AlterField(
            model_name='projectinfoindct',
            name='PrjEngCode2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='PrjEngCode2'),
        ),
        migrations.AlterField(
            model_name='projectinfoindct',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ProjectName'),
        ),
    ]
