# Generated by Django 2.1.7 on 2021-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20201229_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfoindct',
            name='PPA',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PPA'),
        ),
        migrations.AddField(
            model_name='projectinfoindct',
            name='PQE',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='PQE'),
        ),
        migrations.AddField(
            model_name='projectinfoindct',
            name='Type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Type'),
        ),
    ]
