# Generated by Django 2.1.7 on 2019-11-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20191113_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='edit_time',
            field=models.CharField(blank=True, max_length=26, verbose_name='edit_time'),
        ),
    ]
