# Generated by Django 2.1.7 on 2022-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20210928_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
