# Generated by Django 2.1.7 on 2020-03-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20191113_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson_learn',
            options={'verbose_name': 'lesson_learnME', 'verbose_name_plural': 'lesson_learnME'},
        ),
    ]
