# Generated by Django 2.1.7 on 2022-06-09 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_userinfo_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='token',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.UserInfo'),
        ),
    ]
