# Generated by Django 2.1.7 on 2020-03-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200316_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectinfoinDCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.CharField(max_length=5, verbose_name='Year')),
                ('ComPrjCode', models.CharField(max_length=10, verbose_name='ComPrjCode')),
                ('CusPrjCode', models.CharField(max_length=50, verbose_name='CusPrjCode')),
                ('ProjectName', models.CharField(max_length=100, verbose_name='ProjectName')),
                ('Size', models.CharField(max_length=10, verbose_name='Size')),
                ('CPU', models.CharField(max_length=50, verbose_name='CPU')),
                ('Platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('VGA', models.CharField(max_length=1000, verbose_name='VGA')),
                ('OSSupport', models.CharField(max_length=500, verbose_name='OSSupport')),
                ('SS', models.DateTimeField(verbose_name='SS')),
                ('LD', models.CharField(max_length=20, verbose_name='LD')),
                ('DQAPL', models.CharField(max_length=20, verbose_name='DQAPL')),
            ],
        ),
    ]
