# Generated by Django 2.1.7 on 2022-06-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20220609_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'UserToken', 'verbose_name_plural': 'UserToken'},
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(3, 'PM'), (1, '测试部门'), (4, '其它部门'), (2, '开发部门')], default=1, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_SVPuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_token', serialize=False, to='app01.UserInfo', verbose_name='User'),
        ),
    ]
