# Generated by Django 2.1.7 on 2020-05-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20200325_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfoindct',
            name='Platform',
            field=models.CharField(max_length=500, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='projectinfoindct',
            name='ProjectName',
            field=models.CharField(max_length=1000, verbose_name='ProjectName'),
        ),
    ]
