# Generated by Django 2.1.7 on 2022-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20220613_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(2, '开发部门'), (3, 'PM'), (1, '测试部门'), (4, '其它部门')], default=1, verbose_name='部门'),
        ),
    ]
