# Generated by Django 2.1.7 on 2020-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20200722_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='Action',
            field=models.CharField(default='', max_length=2000, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Reproduce_Steps',
            field=models.CharField(default='', max_length=2000, verbose_name='Reproduce_Steps'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Root_Cause',
            field=models.CharField(max_length=2000, verbose_name='Root_Cause'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Solution',
            field=models.CharField(max_length=2000, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Symptom',
            field=models.CharField(max_length=1000),
        ),
    ]
