# Generated by Django 2.1.7 on 2020-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_auto_20200729_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_learn',
            name='Action',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='lesson_learn',
            name='Reproduce_Steps',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Reproduce_Steps'),
        ),
    ]
