# Generated by Django 2.1.7 on 2020-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_auto_20200914_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfoindct',
            name='Customer',
            field=models.CharField(default='', max_length=10, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='projectinfoindct',
            name='ModifiedDate',
            field=models.CharField(default='', max_length=100, verbose_name='ModifiedDate'),
        ),
    ]
