# Generated by Django 2.1.7 on 2023-02-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20220615_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfoindct',
            name='DQAPLNum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DQAPLNum'),
        ),
        migrations.AddField(
            model_name='projectinfoindct',
            name='LDNum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='LDNum'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(3, 'PM'), (4, '其它部门'), (1, '测试部门'), (2, '开发部门')], default=1, verbose_name='部门'),
        ),
    ]
