# Generated by Django 2.1.7 on 2023-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_auto_20230224_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(1, '测试部门'), (2, '开发部门'), (4, '其它部门'), (3, 'PM')], default=1, verbose_name='部门'),
        ),
    ]
