# Generated by Django 2.1.7 on 2023-02-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20230224_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(4, '其它部门'), (3, 'PM'), (2, '开发部门'), (1, '测试部门')], default=1, verbose_name='部门'),
        ),
    ]
