# Generated by Django 2.1.7 on 2024-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_auto_20230307_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_learn',
            name='Status',
            field=models.CharField(blank=True, choices=[('', ''), ('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(2, '开发部门'), (3, 'PM'), (1, '测试部门'), (4, '其它部门')], default=1, verbose_name='部门'),
        ),
    ]
