# Generated by Django 2.1.7 on 2024-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_auto_20240628_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.IntegerField(choices=[(4, '其它部门'), (1, '测试部门'), (2, '开发部门'), (3, 'PM')], default=1, verbose_name='部门'),
        ),
    ]
