# Generated by Django 2.1.7 on 2023-02-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairCabinetLNV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=16, unique=True, verbose_name='統一編號')),
                ('Category', models.CharField(max_length=64, verbose_name='產品類別')),
                ('Area', models.CharField(max_length=64, verbose_name='位置')),
                ('linshi_Area', models.CharField(blank=True, max_length=64, null=True, verbose_name='位置')),
                ('Purpose', models.CharField(blank=True, max_length=256, null=True, verbose_name='臨時用途')),
                ('linshi_Purpose', models.CharField(blank=True, max_length=256, null=True, verbose_name='臨時用途')),
                ('BrwStatus', models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已損壞', '已損壞'), ('維修中', '維修中'), ('申請確認中', '申請確認中'), ('轉帳確認中', '轉帳確認中'), ('申請核准中', '申請核准中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='使用狀態')),
                ('linshi_BrwStatus', models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已損壞', '已損壞'), ('維修中', '維修中'), ('申請確認中', '申請確認中'), ('轉帳確認中', '轉帳確認中'), ('申請核准中', '申請核准中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='臨時使用狀態')),
                ('OAP', models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人')),
                ('OAPcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人工號')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人工號')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='領用日期')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Last_OAP', models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任保管人姓名')),
                ('Last_OAPcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任保管人工號')),
                ('Last_Borrow_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='上一次領用日期')),
                ('Last_Return_date', models.DateField(blank=True, max_length=64, null=True, verbose_name='上一次歸還日期')),
                ('Last_BR_per', models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任使用人')),
                ('Last_BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任使用人工號')),
                ('Last_BrwStatus', models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已損壞', '已損壞'), ('維修中', '維修中'), ('申請確認中', '申請確認中'), ('轉帳確認中', '轉帳確認中'), ('申請核准中', '申請核准中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='上一任使用狀態')),
                ('Transefer_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號')),
                ('Receive_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='接收人員工號')),
                ('Sign_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='簽核人員工號')),
            ],
            options={
                'verbose_name': 'ChairCabinetLNV',
                'verbose_name_plural': 'ChairCabinetLNV',
            },
        ),
        migrations.CreateModel(
            name='ChairCabinetLNVHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=16, verbose_name='統一編號')),
                ('Category', models.CharField(max_length=64, verbose_name='產品類別')),
                ('Area', models.CharField(max_length=64, verbose_name='位置')),
                ('Purpose', models.CharField(blank=True, max_length=256, null=True, verbose_name='用途')),
                ('OAP', models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人')),
                ('OAPcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人工號')),
                ('BrwStatus', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用狀態')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='領用日期')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Changetime', models.DateField(blank=True, max_length=64, null=True, verbose_name='变更使用人日期')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人工號')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人')),
                ('Transefer_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號')),
                ('Receive_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='接收人員工號')),
                ('Comments', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': '柜椅借还记录',
                'verbose_name_plural': '柜椅借还记录',
            },
        ),
    ]
