# Generated by Django 2.1.7 on 2022-02-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='Transefer_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='Changetime',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='变更使用人日期'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='Receive_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='接收人員工號'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='Transefer_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('使用中', '使用中'), ('申請中', '申請中'), ('歸還中', '歸還中'), ('轉帳中', '轉帳中'), ('接收中', '接收中'), ('閒置中', '閒置中'), ('已損壞', '已損壞'), ('申請確認中', '申請確認中'), ('歸還確認中', '歸還確認中'), ('轉帳確認中', '轉帳確認中')], max_length=64, null=True, verbose_name='使用狀態'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='Last_BR_per',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任借用人姓名'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='Last_BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任借用人工號'),
        ),
    ]
