# Generated by Django 2.1.7 on 2022-03-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0005_auto_20220304_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='BrwStatus',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用狀態'),
        ),
    ]
