# Generated by Django 2.1.7 on 2022-03-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0008_auto_20220307_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaircabinetlnv',
            name='RealUsrname',
        ),
        migrations.RemoveField(
            model_name='chaircabinetlnv',
            name='use_per_code',
        ),
        migrations.RemoveField(
            model_name='chaircabinetlnvhis',
            name='Transefer_per_code',
        ),
        migrations.RemoveField(
            model_name='chaircabinetlnvhis',
            name='use_per_code',
        ),
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='OAP',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='OAPcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人工號'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='OAP',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='OAPcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='保管人工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已損壞', '已損壞'), ('維修中', '維修中'), ('申請確認中', '申請確認中'), ('轉帳確認中', '轉帳確認中'), ('申請核准中', '申請核准中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='使用狀態'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='Usrname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnvhis',
            name='BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnvhis',
            name='Usrname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人工號'),
        ),
    ]
