# Generated by Django 2.1.7 on 2022-03-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0009_auto_20220307_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaircabinetlnv',
            name='Last_RealUsrname',
        ),
        migrations.RemoveField(
            model_name='chaircabinetlnv',
            name='Last_use_per_code',
        ),
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='Last_OAP',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任保管人姓名'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='Last_OAPcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任保管人工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='Last_BR_per',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任使用人'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='Last_BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='上一任使用人工號'),
        ),
    ]
