# Generated by Django 2.1.7 on 2022-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0011_chaircabinetlnv_last_brwstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='linshi_BrwStatus',
            field=models.CharField(blank=True, choices=[('使用中', '使用中'), ('閑置中', '閑置中'), ('已損壞', '已損壞'), ('維修中', '維修中'), ('申請確認中', '申請確認中'), ('轉帳確認中', '轉帳確認中'), ('申請核准中', '申請核准中'), ('接收確認中', '接收確認中')], max_length=64, null=True, verbose_name='臨時使用狀態'),
        ),
    ]
