# Generated by Django 2.1.7 on 2022-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0012_chaircabinetlnv_linshi_brwstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaircabinetlnvhis',
            name='RealUsrname',
        ),
        migrations.AddField(
            model_name='chaircabinetlnvhis',
            name='Transefer_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='轉賬人員工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnvhis',
            name='BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人'),
        ),
    ]
