# Generated by Django 2.1.7 on 2022-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0013_auto_20220311_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='linshi_Area',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='chaircabinetlnv',
            name='linshi_Purpose',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='臨時用途'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnv',
            name='Purpose',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='臨時用途'),
        ),
    ]
