# Generated by Django 2.1.7 on 2022-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChairCabinetMS', '0014_auto_20220311_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaircabinetlnvhis',
            name='BR_per_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人工號'),
        ),
        migrations.AlterField(
            model_name='chaircabinetlnvhis',
            name='Usrname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='使用人'),
        ),
    ]
