# Generated by Django 2.1.7 on 2020-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouncing_M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=20)),
                ('Project', models.CharField(max_length=20)),
                ('A_cover', models.CharField(default='', max_length=50)),
                ('C_cover', models.CharField(max_length=50)),
                ('D_cover', models.CharField(max_length=50)),
                ('HS', models.CharField(max_length=50)),
                ('Torque', models.CharField(max_length=10)),
                ('Push', models.CharField(max_length=10)),
                ('PV_L', models.FloatField()),
                ('PV_R', models.FloatField()),
                ('D_L', models.FloatField()),
                ('D_R', models.FloatField()),
                ('Conclusion', models.CharField(max_length=1000)),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
            ],
            options={
                'verbose_name': 'Bouncing',
                'verbose_name_plural': 'Bouncing',
            },
        ),
        migrations.CreateModel(
            name='files_BM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='files_B/', verbose_name='文件内容')),
                ('single', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名称')),
            ],
        ),
        migrations.AddField(
            model_name='bouncing_m',
            name='files_B',
            field=models.ManyToManyField(blank=True, related_name='files_B', to='Bouncing.files_BM', verbose_name='图文件表'),
        ),
    ]
