# Generated by Django 2.1.7 on 2019-09-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouncing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=20)),
                ('Project', models.CharField(max_length=20)),
                ('C_cover', models.CharField(max_length=50)),
                ('D_cover', models.CharField(max_length=50)),
                ('HS', models.CharField(max_length=50)),
                ('Torque', models.CharField(max_length=10)),
                ('Push', models.CharField(max_length=10)),
                ('PV_L', models.FloatField()),
                ('PV_R', models.FloatField()),
                ('D_L', models.FloatField()),
                ('D_R', models.FloatField()),
                ('Conclusion', models.CharField(max_length=1000)),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
            ],
        ),
    ]
