# Generated by Django 2.1.7 on 2019-09-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bouncing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bouncing',
            new_name='Bouncing_M',
        ),
    ]
