# Generated by Django 2.1.7 on 2019-10-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bouncing', '0002_auto_20190920_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouncing_m',
            options={'verbose_name': 'Bouncing', 'verbose_name_plural': 'Bouncing'},
        ),
    ]
