# Generated by Django 2.1.7 on 2019-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bouncing', '0003_auto_20191015_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouncing_m',
            name='A_cover',
            field=models.CharField(default='', max_length=50),
        ),
    ]
