# Generated by Django 2.1.7 on 2021-04-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0002_auto_20210412_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDevCtgryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevCtgry', models.CharField(max_length=512, verbose_name='設備種類')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevpropertiesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devproperties', models.CharField(max_length=256, verbose_name='設備屬性')),
                ('DevCtgry_P', models.ForeignKey(on_delete=True, to='DeviceABO.DeviceDevCtgryList')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevsizeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Devsize', models.CharField(blank=True, max_length=128, null=True, verbose_name='設備容量')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDevVendorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevVendor', models.CharField(max_length=128, verbose_name='設備廠家')),
                ('Devproperties_P', models.ForeignKey(on_delete=True, to='DeviceABO.DeviceDevpropertiesList')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceIntfCtgryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntfCtgry', models.CharField(max_length=64, verbose_name='介面種類')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceABOCategoryList',
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='AssetNum',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='資產編號'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('ABO', 'ABO')], max_length=24, verbose_name='客戶別'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='DeclarationNo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='報關單號'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='LSTA',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='LNV SW Test lab device Audit list: Require state(Must, Optional)'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='PN',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='P/N'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='Plant',
            field=models.CharField(choices=[('', ''), ('KS', 'KS'), ('CQ', 'CQ')], max_length=108, verbose_name='廠區'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='addnewname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='設備添加人員'),
        ),
        migrations.AddField(
            model_name='devicedevsizelist',
            name='DevVendor_P',
            field=models.ForeignKey(on_delete=True, to='DeviceABO.DeviceDevVendorList'),
        ),
        migrations.AddField(
            model_name='devicedevctgrylist',
            name='IntfCtgry_P',
            field=models.ForeignKey(on_delete=True, to='DeviceABO.DeviceIntfCtgryList'),
        ),
    ]
