# Generated by Django 2.1.7 on 2021-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0004_auto_20210414_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLNVHis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID', models.CharField(max_length=16, unique=True, verbose_name='設備序號')),
                ('DevID', models.CharField(max_length=128, verbose_name='設備編號')),
                ('DevModel', models.CharField(max_length=128, verbose_name='設備型號')),
                ('DevName', models.CharField(max_length=1024, verbose_name='設備名稱')),
                ('uscyc', models.CharField(blank=True, max_length=64, null=True, verbose_name='使用次數')),
                ('Btime', models.DateField(blank=True, max_length=64, null=True, verbose_name='借用時間')),
                ('Rtime', models.DateField(blank=True, max_length=64, null=True, verbose_name='歸還日期')),
                ('Usrname', models.CharField(blank=True, max_length=64, null=True, verbose_name='用戶名稱')),
                ('BR_per_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='借還人員工號')),
            ],
            options={
                'verbose_name': '设备借还记录',
                'verbose_name_plural': '设备借还记录',
            },
        ),
        migrations.AlterModelOptions(
            name='deviceabo',
            options={'verbose_name': 'Device_ABO', 'verbose_name_plural': 'Device_ABO'},
        ),
    ]
