# Generated by Django 2.1.7 on 2021-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0005_auto_20210416_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceabo',
            name='ApplicationNo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='申購單號'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='DevID',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='設備用途'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='PN',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='料號'),
        ),
    ]
