# Generated by Django 2.1.7 on 2021-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0006_auto_20210621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceabo',
            name='LSTA',
            field=models.CharField(blank=True, choices=[('Must', 'Must'), ('Optional', 'Optional'), ('Similar', 'Similar')], max_length=256, null=True, verbose_name='LNV SW Test lab device Audit list: Require state(Must, Optional)'),
        ),
        migrations.AlterField(
            model_name='devicelnvhis',
            name='DevID',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='設備編號'),
        ),
    ]
