# Generated by Django 2.1.7 on 2021-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0008_devicelnvhis_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelnvhis',
            name='Plandate',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='預計歸還日期'),
        ),
    ]
