# Generated by Django 2.1.7 on 2021-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0013_deviceabo_last_uscyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceabo',
            name='Comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='備註'),
        ),
    ]
