# Generated by Django 2.1.7 on 2021-09-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0014_auto_20210901_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceabo',
            name='FWVer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='FW Ver.'),
        ),
    ]
