# Generated by Django 2.1.7 on 2021-09-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0016_auto_20210901_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceLNVHis',
            new_name='DeviceABOHis',
        ),
    ]
