# Generated by Django 2.1.7 on 2021-09-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0019_auto_20210909_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceabo',
            name='BrwStatus',
            field=models.CharField(blank=True, choices=[('驗收中', '驗收中'), ('已借出', '已借出'), ('可借用', '可借用'), ('預定確認', '預定確認'), ('歸還確認', '歸還確認'), ('續借確認', '續借確認')], max_length=64, null=True, verbose_name='借還狀態'),
        ),
        migrations.AlterField(
            model_name='deviceabo',
            name='DevStatus',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Fixed', 'Fixed'), ('Long', 'Long'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=64, null=True, verbose_name='設備狀態'),
        ),
    ]
