# Generated by Django 2.1.7 on 2022-07-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceABO', '0020_auto_20210923_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceabo',
            name='EOL',
            field=models.DateField(blank=True, max_length=64, null=True, verbose_name='EOL日期'),
        ),
    ]
