# Generated by Django 2.1.7 on 2022-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0003_auto_20210324_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqm',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], max_length=100, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='cqmproject',
            name='Customer',
            field=models.CharField(choices=[('', ''), ('C38(NB)', 'C38(NB)'), ('C38(NB)-SMB', 'C38(NB)-SMB'), ('C38(AIO)', 'C38(AIO)'), ('T88(AIO)', 'T88(AIO)'), ('A39', 'A39'), ('C85', 'C85'), ('Others', 'Others')], max_length=20, verbose_name='Customer'),
        ),
    ]
