# Generated by Django 2.1.7 on 2020-07-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0003_auto_20200710_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqm',
            name='Comments',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comments'),
        ),
    ]
