# Generated by Django 2.1.7 on 2021-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0005_auto_20201223_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqm',
            name='Keyparts',
            field=models.CharField(max_length=1000, verbose_name='Keyparts'),
        ),
    ]
