# Generated by Django 2.1.7 on 2022-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0006_auto_20221109_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqm_history',
            name='Changecontent',
            field=models.CharField(max_length=10000, verbose_name='Changecontent'),
        ),
        migrations.AlterField(
            model_name='cqm_history',
            name='Changeto',
            field=models.CharField(max_length=10000, verbose_name='Changecontent'),
        ),
    ]
