# Generated by Django 2.1.7 on 2023-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0010_auto_20221109_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqm',
            name='Compatibility',
            field=models.CharField(blank=True, choices=[('', ''), ('Qd', 'Qd'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('T', 'T'), ('F', 'F'), ('DisQ', 'DisQ'), ('Drpd', 'Drpd'), ('Not Build', 'Not Build')], max_length=100, null=True, verbose_name='Compatibility'),
        ),
        migrations.AlterField(
            model_name='cqm',
            name='Reliability',
            field=models.CharField(blank=True, choices=[('', ''), ('Qd', 'Qd'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('T', 'T'), ('F', 'F'), ('DisQ', 'DisQ'), ('Drpd', 'Drpd'), ('Not Build', 'Not Build')], max_length=100, null=True, verbose_name='Reliability'),
        ),
        migrations.AlterField(
            model_name='cqm',
            name='Testresult',
            field=models.CharField(blank=True, choices=[('', ''), ('Qd', 'Qd'), ('Qd_L', 'Qd_L'), ('Qd_C', 'Qd_C'), ('T', 'T'), ('F', 'F'), ('DisQ', 'DisQ'), ('Drpd', 'Drpd'), ('Not Build', 'Not Build')], max_length=100, null=True, verbose_name='Testresult'),
        ),
    ]
