# Generated by Django 2.1.7 on 2023-08-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSR_OSinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OSinfo', models.CharField(max_length=50, verbose_name='申請人工號')),
                ('Editer', models.CharField(max_length=10, verbose_name='添加人')),
                ('EditTime', models.DateField(blank=True, null=True, verbose_name='EditTime')),
            ],
            options={
                'verbose_name': 'OSR系統版本',
                'verbose_name_plural': 'OSR系統版本',
            },
        ),
        migrations.CreateModel(
            name='PerExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proposer_Num', models.CharField(max_length=10, verbose_name='申請人工號')),
                ('Proposer_Name', models.CharField(max_length=20, verbose_name='申請人姓名(中)')),
                ('Department_Code', models.CharField(max_length=20, verbose_name='課別')),
                ('Project', models.CharField(max_length=50, verbose_name='Project')),
                ('SS_Date', models.DateField(blank=True, null=True, verbose_name='SS時間')),
                ('Year', models.CharField(blank=True, max_length=10, null=True, verbose_name='年份')),
                ('Time_Interval', models.CharField(blank=True, max_length=20, null=True, verbose_name='時間區間')),
                ('Phase', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase')),
                ('Role', models.CharField(max_length=20, verbose_name='Role')),
                ('Function', models.CharField(max_length=20, verbose_name='Function')),
                ('SubFunction_Com', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Function-Compatibility')),
                ('KeypartNum', models.CharField(blank=True, max_length=100, null=True, verbose_name='Keypart數量')),
                ('Comments', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comments')),
                ('Approved_Officer', models.CharField(max_length=10, verbose_name='簽核人員工號')),
                ('Status', models.CharField(max_length=10, verbose_name='狀態')),
                ('EditTime', models.DateField(blank=True, null=True, verbose_name='EditTime')),
            ],
            options={
                'verbose_name': '個人測試履歷',
                'verbose_name_plural': '個人測試履歷',
            },
        ),
    ]
