# Generated by Django 2.1.7 on 2023-08-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalExperience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osr_osinfo',
            name='OSinfo',
            field=models.CharField(max_length=50, verbose_name='OSR系統版本'),
        ),
    ]
