# Generated by Django 2.1.7 on 2023-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalExperience', '0004_auto_20230823_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perexperience',
            name='Status',
            field=models.CharField(choices=[('', ''), ('待簽核', '待簽核'), ('同意', '同意'), ('拒絕', '拒絕')], max_length=10, verbose_name='狀態'),
        ),
    ]
