# Generated by Django 2.1.7 on 2021-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0002_auto_20211203_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresult',
            name='Year',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='SS年份'),
        ),
    ]
