# Generated by Django 2.1.7 on 2021-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0003_auto_20211203_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresult',
            name='Number',
            field=models.CharField(max_length=64, verbose_name='No.'),
        ),
    ]
