# Generated by Django 2.1.7 on 2021-12-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0004_auto_20211203_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresult',
            name='AutoItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='AutoResult.AutoItems'),
        ),
        migrations.AlterField(
            model_name='autoresult',
            name='Projectinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='AutoResult.AutoProject'),
        ),
    ]
