# Generated by Django 2.1.7 on 2021-12-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0005_auto_20211203_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoitems',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='autoitems',
            name='Owner',
            field=models.CharField(blank=True, choices=[('N-VA', 'N-VA'), ('VA', 'VA')], max_length=50, null=True, verbose_name='Owner'),
        ),
    ]
