# Generated by Django 2.1.7 on 2022-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQM', '0004_auto_20220104_0956'),
        ('AutoResult', '0007_auto_20211210_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresult',
            name='ProjectinfoCQM',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='CQM.CQMProject'),
        ),
    ]
