# Generated by Django 2.1.7 on 2022-01-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0008_autoresult_projectinfocqm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoitems',
            options={'verbose_name': 'AutoItems', 'verbose_name_plural': 'AutoItems'},
        ),
    ]
