# Generated by Django 2.1.7 on 2022-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0009_auto_20220104_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresult',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ProjectName'),
        ),
    ]
