# Generated by Django 2.1.7 on 2022-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoResult', '0010_auto_20220104_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoitems',
            name='Status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Cancel', 'Cancel'), ('Ongoing', 'Ongoing')], default='', max_length=50, verbose_name='Status'),
        ),
    ]
