# Generated by Django 2.1.7 on 2019-09-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=20)),
                ('Project', models.CharField(max_length=20)),
                ('SS_Data', models.CharField(max_length=20)),
                ('C_cover_Material', models.CharField(max_length=50)),
                ('D_cover_Material', models.CharField(max_length=50)),
                ('SKU_NO', models.CharField(max_length=10)),
                ('Point1', models.FloatField()),
                ('Point2', models.FloatField()),
                ('Point3', models.FloatField()),
                ('Point4', models.FloatField()),
                ('Point5', models.FloatField()),
                ('Point6', models.FloatField()),
                ('Point7', models.FloatField()),
                ('Ave', models.FloatField()),
                ('Conclusion', models.CharField(max_length=1000)),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(max_length=26, verbose_name='edit_time')),
            ],
        ),
    ]
