# Generated by Django 2.1.7 on 2019-10-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CDM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdm',
            options={'verbose_name': 'CDM', 'verbose_name_plural': 'CDM'},
        ),
    ]
