# Generated by Django 2.1.7 on 2024-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0025_auto_20230307_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABOfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='videos/ABO/Lesson/', verbose_name='视频内容')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='视频名称')),
            ],
        ),
        migrations.CreateModel(
            name='ABOImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/ABO/Lesson/', verbose_name='图片地址')),
                ('single', models.CharField(blank=True, max_length=200, null=True, verbose_name='图片名称')),
            ],
        ),
        migrations.CreateModel(
            name='ABOlesson_learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('', ''), ('Reliability', 'Reliability'), ('Compatibility', 'Compatibility')], default='Reliability', max_length=100)),
                ('Object', models.CharField(max_length=100)),
                ('Symptom', models.CharField(max_length=1000)),
                ('Reproduce_Steps', models.CharField(blank=True, default='', max_length=2000, verbose_name='Reproduce_Steps')),
                ('Root_Cause', models.CharField(max_length=2000, verbose_name='Root_Cause')),
                ('Solution', models.CharField(max_length=2000, verbose_name='Solution')),
                ('Action', models.CharField(blank=True, default='', max_length=2000, verbose_name='Action')),
                ('editor', models.CharField(max_length=100)),
                ('edit_time', models.CharField(blank=True, max_length=26, verbose_name='edit_time')),
                ('Photo', models.ManyToManyField(blank=True, related_name='imgs', to='ABOProjectLessonL.ABOImgs', verbose_name='图片表')),
                ('video', models.ManyToManyField(blank=True, related_name='video', to='ABOProjectLessonL.ABOfiles', verbose_name='视频表')),
            ],
            options={
                'verbose_name': 'ABOlesson_learn',
                'verbose_name_plural': 'ABOlesson_learn',
            },
        ),
        migrations.CreateModel(
            name='ABOlessonlearn_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('', ''), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/S', 'N/S'), ('N/A', 'N/A'), ('N/P', 'N/P')], max_length=20)),
                ('Comment', models.CharField(max_length=1000)),
                ('editor', models.CharField(default='', max_length=100)),
                ('edit_time', models.CharField(blank=True, default='', max_length=26, verbose_name='edit_time')),
            ],
        ),
        migrations.CreateModel(
            name='ABOTestProjectLL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(choices=[('', ''), ('T88(NB)', 'T88(NB)'), ('ABO', 'ABO'), ('Others', 'Others')], max_length=20, verbose_name='Customer')),
                ('Project', models.CharField(max_length=20, unique=True, verbose_name='Project')),
                ('Owner', models.ManyToManyField(to='app01.UserInfo')),
            ],
            options={
                'verbose_name': 'ABOTestProjectLL',
                'verbose_name_plural': 'ABOTestProjectLL',
            },
        ),
        migrations.AddField(
            model_name='abolessonlearn_project',
            name='Projectinfo',
            field=models.ForeignKey(on_delete=True, to='ABOProjectLessonL.ABOTestProjectLL'),
        ),
        migrations.AddField(
            model_name='abolessonlearn_project',
            name='lesson',
            field=models.ForeignKey(on_delete=True, to='ABOProjectLessonL.ABOlesson_learn'),
        ),
    ]
