# Generated by Django 2.1.7 on 2024-05-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABOProjectLessonL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abolesson_learn',
            name='Status',
            field=models.CharField(blank=True, choices=[('', ''), ('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
