# Generated by Django 2.1.7 on 2024-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectComparison', '0002_auto_20240329_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='Compal_Model',
            field=models.CharField(max_length=200, verbose_name='Compal Model'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Customer_Model',
            field=models.CharField(max_length=400, verbose_name='Customer Model'),
        ),
    ]
