# Generated by Django 2.1.7 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectComparison', '0003_auto_20240329_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectplan',
            name='Apr',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Apr'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Aug',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Aug'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Dec',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Dec'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Feb',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Feb'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Jan',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Jan'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Jul',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Jul'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Jun',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Jun'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Mar',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Mar'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='May',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Nov',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Nov'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Oct',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Oct'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='Sep',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sep'),
        ),
    ]
