# Generated by Django 2.1.7 on 2024-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectComparison', '0004_auto_20240329_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='RD_Project_Plan',
            field=models.CharField(default='', max_length=12, verbose_name='RD_Project_Plan'),
        ),
    ]
